# Label configuration for actions/labeler
# See: https://github.com/actions/labeler

rust:
  - changed-files:
      - any-glob-to-any-file: 'model_gateway/src/**/*.rs'

python-bindings:
  - changed-files:
      - any-glob-to-any-file: 'bindings/python/**/*'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**/*'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - '**/Cargo.toml'
          - '**/Cargo.lock'
          - '**/pyproject.toml'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'

grpc:
  - changed-files:
      - any-glob-to-any-file:
          - 'grpc_client/**/*'

mcp:
  - changed-files:
      - any-glob-to-any-file: 'mcp/**/*'

tokenizer:
  - changed-files:
      - any-glob-to-any-file: 'tokenizer/**/*'

tool-parser:
  - changed-files:
      - any-glob-to-any-file: 'tool_parser/**/*'

wasm:
  - changed-files:
      - any-glob-to-any-file:
          - 'wasm/**/*'
          - 'model_gateway/src/wasm/**/*'

benchmarks:
  - changed-files:
      - any-glob-to-any-file: 'model_gateway/benches/**/*'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'model_gateway/tests/**/*'
          - 'e2e_test/**/*'
