-- V1: Create the existing RESPONSES table (as it exists in genai-data-plane)
-- This represents the pre-migration baseline schema.

CREATE TABLE RESPONSES (
    RESPONSE_ID              VARCHAR2(255)              NOT NULL,
    CONVERSATION_ID          VARCHAR2(255),
    PREVIOUS_RESPONSE_ID     VARCHAR2(255),
    INPUT_ITEMS              CLOB,
    RESPONSE_OBJECT          CLOB,
    MODEL                    VARCHAR2(255),
    CREATED_AT               TIMESTAMP WITH TIME ZONE,
    CONVERSATION_STORE_ID    VARCHAR2(255),
    GENERATIVE_AI_PROJECT_ID VARCHAR2(255),
    SUBJECT_ID               VARCHAR2(255),
    EXPIRES_AT               TIMESTAMP WITH TIME ZONE,
    CONSTRAINT PK_RESPONSES PRIMARY KEY (RESPONSE_ID)
);

-- Indexes for common query patterns
CREATE INDEX IDX_RESPONSES_CONV_ID ON RESPONSES (CONVERSATION_ID);
CREATE INDEX IDX_RESPONSES_EXPIRES_AT ON RESPONSES (EXPIRES_AT);
CREATE INDEX IDX_RESPONSES_CREATED_AT ON RESPONSES (CREATED_AT);
