runnerTag = "latest"
name = "smg"
team = "GenAI"
phoneBookId = "ocasgs"
description = "Shepherd Model Gateway"

majorversion = 0
minorversion = 1
shortversion = ${majorversion}.${minorversion}
snapshotVersion = ${shortversion}-SNAPSHOT
version = ${shortversion}${?BLD_BRANCH_SUFFIX}.${BLD_NUMBER}${?BLD_SNAPSHOT_SUFFIX}
triggerOnCommitBranches = ["master", "pull-requests", "feature*"]
releaseBranches = ["master", "pull-requests", "feature*"]

initialBuildNumber = {
  "master": 1,
  "*": 1
}

sendNotificationBranches = ["master", "pull-requests"]
slackChannels = []

authCompartmentOcid = "ocid1.tenancy.oc1..aaaaaaaakyvertmo4tineubnzxftatozvqmdh6anb3bplvdqgsg3y63ctzjq"

steps = [
  {
    name = "build",
    type = "make",
    environment = {
      "RUNNER_PROXY": "www-proxy-hqdc.us.oracle.com:80",
      "HTTPS_PROXY": "www-proxy-hqdc.us.oracle.com:80",
      "HTTP_PROXY": "www-proxy-hqdc.us.oracle.com:80",
      "NO_PROXY": ".oraclecorp.com",
      "https_proxy": "www-proxy-hqdc.us.oracle.com:80",
      "http_proxy": "www-proxy-hqdc.us.oracle.com:80",
      "no_proxy": ".oraclecorp.com"
    },
    makeCommands = [
      { target = "test" }
    ]
  }
]
