runnerTag: latest
name: smg
team: GenAI
phoneBookId: ocasgs
description: Shepherd Model Gateway

majorversion: 0
minorversion: 1
shortversion: ${majorversion}.${minorversion}
snapshotVersion: ${shortversion}-SNAPSHOT
version: ${shortversion}${?BLD_BRANCH_SUFFIX}.${BLD_NUMBER}${?BLD_SNAPSHOT_SUFFIX}
triggerOnCommitBranches: ["main", "pull-requests", "feature*"]
releaseBranches: ["main", "feature*"]

initialBuildNumber: {
  "main": 1
  "*": 1
}

sendNotificationBranches: ["main", "pull-requests"]
slackChannels: []

authCompartmentOcid: ocid1.tenancy.oc1..aaaaaaaakyvertmo4tineubnzxftatozvqmdh6anb3bplvdqgsg3y63ctzjq
pipelineId: ocid1.devopsbuildpipeline.oc1.phx.amaaaaaay3l4rjaaxwy23xv5baylbdbeowpznskclflsyypdrb6rfrn3fvsq

steps: [
  {
    name: format-check
    type: make
    runnerImage: build-runner-make-ol9
    environment: {
      "RUNNER_PROXY": "http://www-proxy-hqdc.us.oracle.com:80"
      "HTTPS_PROXY": "http://www-proxy-hqdc.us.oracle.com:80"
      "HTTP_PROXY": "http://www-proxy-hqdc.us.oracle.com:80"
      "NO_PROXY": "127.0.0.1,localhost,.oraclecorp.com"
      "https_proxy": "http://www-proxy-hqdc.us.oracle.com:80"
      "http_proxy": "http://www-proxy-hqdc.us.oracle.com:80"
      "no_proxy": "127.0.0.1,localhost,.oraclecorp.com"
    }
    makeCommands: [
      { target: "setup-rust" }
      { target: "check" }
      { target: "lint" }
      { target: "fmt" }
    ]
    artifacts: [
      "**"
    ]
  },
  {
    name: unit-test
    type: make
    runnerImage: build-runner-make-ol9
    environment: {
      "RUNNER_PROXY": "http://www-proxy-hqdc.us.oracle.com:80"
      "HTTPS_PROXY": "http://www-proxy-hqdc.us.oracle.com:80"
      "HTTP_PROXY": "http://www-proxy-hqdc.us.oracle.com:80"
      "NO_PROXY": "127.0.0.1,localhost,.oraclecorp.com"
      "https_proxy": "http://www-proxy-hqdc.us.oracle.com:80"
      "http_proxy": "http://www-proxy-hqdc.us.oracle.com:80"
      "no_proxy": "127.0.0.1,localhost,.oraclecorp.com"
    }
    makeCommands: [
      { target: "setup-rust" }
      { target: "test" }
    ]
  },
  {
    name: build-image
    type: dockerizer
    environment: {
      "RUNNER_PROXY": "http://www-proxy-hqdc.us.oracle.com:80"
      "HTTPS_PROXY": "http://www-proxy-hqdc.us.oracle.com:80"
      "HTTP_PROXY": "http://www-proxy-hqdc.us.oracle.com:80"
      "NO_PROXY": "127.0.0.1,localhost,.oraclecorp.com"
      "https_proxy": "http://www-proxy-hqdc.us.oracle.com:80"
      "http_proxy": "http://www-proxy-hqdc.us.oracle.com:80"
      "no_proxy": "127.0.0.1,localhost,.oraclecorp.com"
    }
    dockerFile: "docker/oci.Dockerfile"
    dockerBuildPwd: "."
  },
  {
    name: publish-image
    type: publishdocker
    dependsOn: build-image
    repository: odo-docker-signed-local
    imageName: ${name}
  },
  {
    type: helm
    name: package-helm
    helmCommands: [
      {command: "version"},
      {command: "dependency update ./helm"},
      {command: "package -d build/ ./helm --version "${version}}
    ]
    artifacts: ["**"]
  },
  {
    name: publish-helm
    type: publishgeneric
    dependsOn: package-helm
    repository: shepherd-release-helm-local
    filePathsToPublish: [
      {
        localFile: "build/*.tgz"
        targetDir: "/"
      }
    ]
  },
]
