runnerTag: latest
name: smg
team: GenAI
phoneBookId: ocasgs
description: Shepherd Model Gateway

majorversion: 0
minorversion: 1
shortversion: ${majorversion}.${minorversion}
snapshotVersion: ${shortversion}-SNAPSHOT
version: ${shortversion}${?BLD_BRANCH_SUFFIX}.${BLD_NUMBER}${?BLD_SNAPSHOT_SUFFIX}
triggerOnCommitBranches: ["main", "pull-requests", "feature*"]
releaseBranches: ["main", "pull-requests", "feature*"]

initialBuildNumber: {
  "main": 1
  "*": 1
}

sendNotificationBranches: ["main", "pull-requests"]
slackChannels: []

authCompartmentOcid: ocid1.tenancy.oc1..aaaaaaaakyvertmo4tineubnzxftatozvqmdh6anb3bplvdqgsg3y63ctzjq
pipelineId: ocid1.devopsbuildpipeline.oc1.phx.amaaaaaay3l4rjaaxwy23xv5baylbdbeowpznskclflsyypdrb6rfrn3fvsq

steps: [
  {
    name: build
    type: make
    environment: {
      "RUNNER_PROXY": "www-proxy-hqdc.us.oracle.com:80"
      "HTTPS_PROXY": "www-proxy-hqdc.us.oracle.com:80"
      "HTTP_PROXY": "www-proxy-hqdc.us.oracle.com:80"
      "NO_PROXY": ".oraclecorp.com"
      "https_proxy": "www-proxy-hqdc.us.oracle.com:80"
      "http_proxy": "www-proxy-hqdc.us.oracle.com:80"
      "no_proxy": ".oraclecorp.com"
    }
    makeCommands: [
      { target: "test" }
    ]
  }
]
