name: 'Check CI Gate'
description: 'Determine if CI should run based on author association and labels'

outputs:
  should_run:
    description: 'Whether CI should run'
    value: ${{ steps.check.outputs.should_run }}

runs:
  using: 'composite'
  steps:
    - id: check
      shell: bash
      run: |
        EVENT="${{ github.event_name }}"
        AUTHOR="${{ github.event.pull_request.author_association }}"
        ACTOR="${{ github.actor }}"
        LABEL="${{ github.event.label.name }}"
        HAS_RUN_CI="${{ contains(github.event.pull_request.labels.*.name, 'run-ci') }}"

        should_run="false"
        reason=""

        if [[ "$EVENT" != "pull_request" ]]; then
          should_run="true"
          reason="not a pull request ($EVENT)"
        elif [[ "$ACTOR" == "dependabot[bot]" ]]; then
          should_run="true"
          reason="Dependabot"
        elif [[ "$AUTHOR" =~ ^(OWNER|MEMBER|COLLABORATOR)$ ]]; then
          should_run="true"
          reason="trusted contributor ($AUTHOR)"
        elif [[ "${{ github.event.action }}" == "labeled" && "$LABEL" == "run-ci" ]]; then
          should_run="true"
          reason="run-ci label added"
        elif [[ "$HAS_RUN_CI" == "true" ]]; then
          should_run="true"
          reason="has run-ci label"
        fi

        echo "should_run=${should_run}" >> $GITHUB_OUTPUT

        if [[ "$should_run" == "true" ]]; then
          echo "✅ CI allowed: $reason"
        else
          echo "::notice::CI skipped for external contributor ($AUTHOR). Add 'run-ci' label to run."
        fi
