//! Schema configuration for storage backends.
//!
//! Provides YAML-driven customization of table names and column names.
//! When no schema config is provided, all defaults match the current
//! hardcoded behavior — zero behavioral change.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

// ────────────────────────────────────────────────────────────────────────────
// Types
// ────────────────────────────────────────────────────────────────────────────

/// Top-level schema configuration. Drives all SQL generation and key naming.
///
/// Every field has a default matching current hardcoded behavior, so omitting
/// the entire `schema:` section in YAML produces identical queries to today.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(default)]
pub struct SchemaConfig {
    /// Schema owner / key prefix (e.g. `"ADMIN"` for Oracle, `"myapp"` for Redis).
    /// The dot in `ADMIN."TABLE"` is generated by `qualified_table()`, not stored here.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,

    pub conversations: TableConfig,
    pub responses: TableConfig,
    pub conversation_items: TableConfig,
    pub conversation_item_links: TableConfig,
}

/// Per-table schema configuration.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[serde(default)]
pub struct TableConfig {
    /// Physical table name (or Redis key component).
    pub table: String,

    /// Column name overrides: `logical_name -> db_column_name`.
    /// Fields not listed here use their logical name unchanged.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub columns: HashMap<String, String>,
}

// ────────────────────────────────────────────────────────────────────────────
// Defaults
// ────────────────────────────────────────────────────────────────────────────

impl Default for SchemaConfig {
    fn default() -> Self {
        Self {
            owner: None,
            conversations: TableConfig::with_table("conversations"),
            responses: TableConfig::with_table("responses"),
            conversation_items: TableConfig::with_table("conversation_items"),
            conversation_item_links: TableConfig::with_table("conversation_item_links"),
        }
    }
}

// ────────────────────────────────────────────────────────────────────────────
// TableConfig methods
// ────────────────────────────────────────────────────────────────────────────

impl TableConfig {
    /// Create a `TableConfig` with the given table name and no column overrides.
    pub fn with_table(name: &str) -> Self {
        Self {
            table: name.to_string(),
            ..Default::default()
        }
    }

    /// Resolve a column name.
    ///
    /// Returns the remapped name if an override is configured, or the
    /// logical field name unchanged otherwise.
    pub fn col<'a>(&'a self, field: &'a str) -> &'a str {
        self.columns.get(field).map(String::as_str).unwrap_or(field)
    }

    /// Fully qualified table name, e.g. `ADMIN."CONVERSATIONS"` with an owner
    /// or just `conversations` without.
    pub fn qualified_table(&self, owner: Option<&str>) -> String {
        match owner {
            Some(o) => format!("{o}.\"{}\"", self.table),
            None => self.table.clone(),
        }
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Validation
// ────────────────────────────────────────────────────────────────────────────

impl SchemaConfig {
    /// Validate the entire schema config at startup. Rejects invalid identifiers.
    pub fn validate(&self) -> Result<(), String> {
        // Validate owner
        if let Some(ref owner) = self.owner {
            validate_identifier(owner).map_err(|e| format!("owner: {e}"))?;
        }

        // Validate each table config
        Self::validate_table("conversations", &self.conversations)?;
        Self::validate_table("responses", &self.responses)?;
        Self::validate_table("conversation_items", &self.conversation_items)?;
        Self::validate_table("conversation_item_links", &self.conversation_item_links)?;

        Ok(())
    }

    fn validate_table(label: &str, tc: &TableConfig) -> Result<(), String> {
        validate_identifier(&tc.table).map_err(|e| format!("{label}.table: {e}"))?;

        for (logical, physical) in &tc.columns {
            validate_identifier(logical)
                .map_err(|e| format!("{label}.columns key '{logical}': {e}"))?;
            validate_identifier(physical)
                .map_err(|e| format!("{label}.columns value '{physical}': {e}"))?;
        }

        Ok(())
    }
}

/// Reject identifiers that are empty or contain characters outside `[a-zA-Z0-9_]`.
fn validate_identifier(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("identifier must not be empty".to_string());
    }
    if !name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
        return Err(format!(
            "invalid identifier '{name}' — only ASCII alphanumeric and underscores allowed"
        ));
    }
    Ok(())
}

// ────────────────────────────────────────────────────────────────────────────
// Tests
// ────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Default config ────────────────────────────────────────────────────

    #[test]
    fn default_config_matches_hardcoded_names() {
        let cfg = SchemaConfig::default();
        assert_eq!(cfg.conversations.table, "conversations");
        assert_eq!(cfg.responses.table, "responses");
        assert_eq!(cfg.conversation_items.table, "conversation_items");
        assert_eq!(cfg.conversation_item_links.table, "conversation_item_links");
        assert!(cfg.owner.is_none());
    }

    #[test]
    fn default_config_validates_successfully() {
        SchemaConfig::default()
            .validate()
            .expect("default config should be valid");
    }

    // ── col() ─────────────────────────────────────────────────────────────

    #[test]
    fn col_returns_field_name_when_no_override() {
        let tc = TableConfig::with_table("t");
        assert_eq!(tc.col("id"), "id");
        assert_eq!(tc.col("created_at"), "created_at");
    }

    #[test]
    fn col_returns_override_when_configured() {
        let mut tc = TableConfig::with_table("t");
        tc.columns
            .insert("id".to_string(), "CONVERSATION_ID".to_string());
        assert_eq!(tc.col("id"), "CONVERSATION_ID");
        // Non-overridden field still returns itself
        assert_eq!(tc.col("created_at"), "created_at");
    }

    // ── qualified_table() ─────────────────────────────────────────────────

    #[test]
    fn qualified_table_without_owner() {
        let tc = TableConfig::with_table("conversations");
        assert_eq!(tc.qualified_table(None), "conversations");
    }

    #[test]
    fn qualified_table_with_owner() {
        let tc = TableConfig::with_table("CONVERSATIONS");
        assert_eq!(tc.qualified_table(Some("ADMIN")), "ADMIN.\"CONVERSATIONS\"");
    }

    // ── validate() ────────────────────────────────────────────────────────

    #[test]
    fn validate_accepts_valid_identifiers() {
        let mut cfg = SchemaConfig {
            owner: Some("ADMIN_01".to_string()),
            ..Default::default()
        };
        cfg.conversations.table = "MY_CONVERSATIONS".to_string();
        cfg.conversations
            .columns
            .insert("id".to_string(), "CONV_ID".to_string());
        cfg.validate().expect("should be valid");
    }

    #[test]
    fn validate_rejects_empty_table_name() {
        let mut cfg = SchemaConfig::default();
        cfg.conversations.table = String::new();
        let err = cfg.validate().unwrap_err();
        assert!(
            err.contains("conversations.table") && err.contains("empty"),
            "unexpected: {err}"
        );
    }

    #[test]
    fn validate_rejects_special_characters() {
        let mut cfg = SchemaConfig::default();
        cfg.conversations.table = "table;DROP".to_string();
        let err = cfg.validate().unwrap_err();
        assert!(
            err.contains("conversations.table") && err.contains("invalid identifier"),
            "unexpected: {err}"
        );
    }

    #[test]
    fn validate_rejects_dots_in_owner() {
        let cfg = SchemaConfig {
            owner: Some("ADMIN.SCHEMA".to_string()),
            ..Default::default()
        };
        let err = cfg.validate().unwrap_err();
        assert!(
            err.contains("owner") && err.contains("invalid identifier"),
            "unexpected: {err}"
        );
    }

    #[test]
    fn validate_rejects_invalid_column_override_key() {
        let mut cfg = SchemaConfig::default();
        cfg.responses
            .columns
            .insert("bad;col".to_string(), "GOOD_COL".to_string());
        let err = cfg.validate().unwrap_err();
        assert!(
            err.contains("columns key") && err.contains("invalid identifier"),
            "unexpected: {err}"
        );
    }

    #[test]
    fn validate_rejects_invalid_column_override_value() {
        let mut cfg = SchemaConfig::default();
        cfg.responses
            .columns
            .insert("id".to_string(), "bad column!".to_string());
        let err = cfg.validate().unwrap_err();
        assert!(
            err.contains("columns value") && err.contains("invalid identifier"),
            "unexpected: {err}"
        );
    }

    // ── Serde roundtrip ───────────────────────────────────────────────────

    #[test]
    fn serde_roundtrip_default() {
        let cfg = SchemaConfig::default();
        let json = serde_json::to_string(&cfg).expect("serialize");
        let restored: SchemaConfig = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(cfg, restored);
    }

    #[test]
    fn serde_roundtrip_custom() {
        let mut cfg = SchemaConfig {
            owner: Some("ADMIN".to_string()),
            ..Default::default()
        };
        cfg.conversations.table = "CONVERSATIONS".to_string();
        cfg.conversations
            .columns
            .insert("id".to_string(), "CONVERSATION_ID".to_string());

        let json = serde_json::to_string(&cfg).expect("serialize");
        let restored: SchemaConfig = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(cfg, restored);
    }

    #[test]
    fn serde_deserialize_empty_object_uses_defaults() {
        let cfg: SchemaConfig = serde_json::from_str("{}").expect("deserialize empty");
        assert_eq!(cfg, SchemaConfig::default());
    }
}
