# generated by datamodel-codegen:
#   filename:  smg-openapi.yaml
#   timestamp: 2026-02-27T13:47:01+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Type(Enum):
    ephemeral = 'ephemeral'


class CacheControl1(BaseModel):
    type: Type


class CacheControl(RootModel[CacheControl1]):
    root: Annotated[CacheControl1, Field(description='Cache control configuration')]


class CacheCreation(BaseModel):
    pass


class StopTokenId(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class Byte(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class Role(Enum):
    system = 'system'


class Role1(Enum):
    user = 'user'


class Role2(Enum):
    assistant = 'assistant'


class Role3(Enum):
    tool = 'tool'


class Role4(Enum):
    function = 'function'


class ChatMessage5(BaseModel):
    content: str
    name: str
    role: Role4


class Role5(Enum):
    developer = 'developer'


class Type1(Enum):
    char_location = 'char_location'


class Citation1(BaseModel):
    cited_text: str
    document_index: Annotated[int, Field(ge=0)]
    document_title: str | None = None
    end_char_index: Annotated[int, Field(ge=0)]
    file_id: str | None = None
    start_char_index: Annotated[int, Field(ge=0)]
    type: Type1


class Type2(Enum):
    page_location = 'page_location'


class Citation2(BaseModel):
    cited_text: str
    document_index: Annotated[int, Field(ge=0)]
    document_title: str | None = None
    end_page_number: Annotated[int, Field(ge=0)]
    start_page_number: Annotated[int, Field(ge=0)]
    type: Type2


class Type3(Enum):
    content_block_location = 'content_block_location'


class Citation3(BaseModel):
    cited_text: str
    document_index: Annotated[int, Field(ge=0)]
    document_title: str | None = None
    end_block_index: Annotated[int, Field(ge=0)]
    start_block_index: Annotated[int, Field(ge=0)]
    type: Type3


class Type4(Enum):
    web_search_result_location = 'web_search_result_location'


class Citation4(BaseModel):
    cited_text: str
    encrypted_index: str
    title: str | None = None
    type: Type4
    url: str


class Type5(Enum):
    search_result_location = 'search_result_location'


class Citation5(BaseModel):
    cited_text: str
    end_block_index: Annotated[int, Field(ge=0)]
    search_result_index: Annotated[int, Field(ge=0)]
    source: str
    start_block_index: Annotated[int, Field(ge=0)]
    title: str | None = None
    type: Type5


class CitationsConfig(BaseModel):
    enabled: bool | None = None


class ClassifyData(BaseModel):
    index: Annotated[
        int, Field(description='Index of this result (for batch requests)', ge=0)
    ]
    label: Annotated[
        str, Field(description='Predicted class label (from id2label mapping)')
    ]
    num_classes: Annotated[int, Field(description='Number of classes', ge=0)]
    probs: Annotated[
        list[float],
        Field(
            description='Probability distribution over all classes (softmax of logits)'
        ),
    ]


class ClassifyRequest(BaseModel):
    input: Annotated[
        Any,
        Field(
            description='Input can be a string, array of strings, or token IDs - Single string: "text to classify" - Array of strings: ["text1", "text2"] - Token IDs: [1, 2, 3] (advanced usage)'
        ),
    ]
    log_metrics: Annotated[
        bool | None,
        Field(description='SGLang extension: enable/disable logging of metrics'),
    ] = None
    model: Annotated[str, Field(description='ID of the model to use')]
    priority: Annotated[
        int | None, Field(description='SGLang extension: request priority')
    ] = None
    rid: Annotated[
        str | None, Field(description='SGLang extension: request id for tracking')
    ] = None
    user: Annotated[str | None, Field(description='Optional user identifier')] = None


class CodeInterpreterCallStatus(Enum):
    in_progress = 'in_progress'
    completed = 'completed'
    incomplete = 'incomplete'
    interpreting = 'interpreting'
    failed = 'failed'


class Type6(Enum):
    logs = 'logs'


class CodeInterpreterOutput1(BaseModel):
    logs: str
    type: Type6


class Type7(Enum):
    image = 'image'


class CodeInterpreterOutput2(BaseModel):
    type: Type7
    url: str


class CompletionTokensDetails(BaseModel):
    reasoning_tokens: Annotated[int | None, Field(ge=0)] = None


class ConnectionMode1(Enum):
    http = 'http'


class ConnectionMode2(Enum):
    grpc = 'grpc'


class ContainerConfig(BaseModel):
    id: Annotated[
        str | None, Field(description='Container ID for reuse across requests')
    ] = None
    skills: Annotated[
        list[str] | None, Field(description='Skills to be loaded in the container')
    ] = None


class Type8(Enum):
    text = 'text'


class ContentBlock1(BaseModel):
    citations: (
        list[Citation1 | Citation2 | Citation3 | Citation4 | Citation5] | None
    ) = None
    text: str
    type: Type8


class Type9(Enum):
    tool_use = 'tool_use'


class ContentBlock2(BaseModel):
    id: str
    input: Any
    name: str
    type: Type9


class Type10(Enum):
    thinking = 'thinking'


class ContentBlock3(BaseModel):
    signature: str
    thinking: str
    type: Type10


class Type11(Enum):
    redacted_thinking = 'redacted_thinking'


class ContentBlock4(BaseModel):
    data: str
    type: Type11


class Type12(Enum):
    server_tool_use = 'server_tool_use'


class ContentBlock5(BaseModel):
    id: str
    input: Any
    name: str
    type: Type12


class Type13(Enum):
    web_search_tool_result = 'web_search_tool_result'


class Type14(Enum):
    tool_search_tool_result = 'tool_search_tool_result'


class Type15(Enum):
    tool_reference = 'tool_reference'


class ContentBlock8(BaseModel):
    description: str | None = None
    tool_name: str
    type: Type15


class Type16(Enum):
    mcp_tool_use = 'mcp_tool_use'


class ContentBlock9(BaseModel):
    id: str
    input: Any
    name: str
    server_name: str
    type: Type16


class Type17(Enum):
    mcp_tool_result = 'mcp_tool_result'


class Type18(Enum):
    text_delta = 'text_delta'


class ContentBlockDelta1(BaseModel):
    text: str
    type: Type18


class Type19(Enum):
    input_json_delta = 'input_json_delta'


class ContentBlockDelta2(BaseModel):
    partial_json: str
    type: Type19


class Type20(Enum):
    thinking_delta = 'thinking_delta'


class ContentBlockDelta3(BaseModel):
    thinking: str
    type: Type20


class Type21(Enum):
    signature_delta = 'signature_delta'


class ContentBlockDelta4(BaseModel):
    signature: str
    type: Type21


class Type22(Enum):
    citations_delta = 'citations_delta'


class ContentBlockDelta5(BaseModel):
    citation: Annotated[
        Citation1 | Citation2 | Citation3 | Citation4 | Citation5,
        Field(description='Citation types'),
    ]
    type: Type22


class Type23(Enum):
    text = 'text'


class ContentPart1(BaseModel):
    text: str
    type: Type23


class Type24(Enum):
    image_url = 'image_url'


class Type25(Enum):
    video_url = 'video_url'


class Detail(Enum):
    low = 'low'
    high = 'high'
    auto = 'auto'


class Type26(Enum):
    base64 = 'base64'


class DocumentSource1(BaseModel):
    data: str
    media_type: str
    type: Type26


class Type27(Enum):
    text = 'text'


class DocumentSource2(BaseModel):
    data: str
    type: Type27


class Type28(Enum):
    url = 'url'


class DocumentSource3(BaseModel):
    type: Type28
    url: str


class Type29(Enum):
    content = 'content'


class EmbeddingObject(BaseModel):
    embedding: list[float]
    index: Annotated[int, Field(ge=0)]
    object: str


class EmbeddingRequest(BaseModel):
    dimensions: Annotated[
        int | None,
        Field(description='Optional number of dimensions for the embedding', ge=0),
    ] = None
    encoding_format: Annotated[
        str | None,
        Field(description='Optional encoding format (e.g., "float", "base64")'),
    ] = None
    input: Annotated[
        Any,
        Field(
            description='Input can be a string, array of strings, tokens, or batch inputs'
        ),
    ]
    log_metrics: Annotated[
        bool | None,
        Field(
            description='SGLang extension: enable/disable logging of metrics for this request'
        ),
    ] = None
    model: Annotated[str, Field(description='ID of the model to use')]
    rid: Annotated[
        str | None, Field(description='SGLang extension: request id for tracking')
    ] = None
    user: Annotated[str | None, Field(description='Optional user identifier')] = None


class ErrorDetail(BaseModel):
    code: str | None = None
    message: str
    param: str | None = None
    type: str


class ErrorResponse(BaseModel):
    error: ErrorDetail


class FileSearchCallStatus(Enum):
    in_progress = 'in_progress'
    searching = 'searching'
    completed = 'completed'
    incomplete = 'incomplete'
    failed = 'failed'


class FileSearchResult(BaseModel):
    attributes: Any | None = None
    file_id: str
    filename: str
    score: float | None = None
    text: str | None = None


class Function(BaseModel):
    description: str | None = None
    name: str
    parameters: Any
    strict: Annotated[
        bool | None,
        Field(
            description='Whether to enable strict schema adherence (OpenAI structured outputs)'
        ),
    ] = None


class FunctionCall1(Enum):
    none = 'none'
    auto = 'auto'


class FunctionCall2(BaseModel):
    name: str


class FunctionCallDelta(BaseModel):
    arguments: str | None = None
    name: str | None = None


class FunctionCallResponse(BaseModel):
    arguments: str | None = None
    name: str


class FunctionChoice(BaseModel):
    name: str


class GenerateFinishType(Enum):
    length = 'length'
    stop = 'stop'


class TokenIdsLogprobItem(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class OutputId(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class HealthCheckUpdate(BaseModel):
    check_interval_secs: Annotated[int | None, Field(ge=0)] = None
    disable_health_check: bool | None = None
    failure_threshold: Annotated[int | None, Field(ge=0)] = None
    success_threshold: Annotated[int | None, Field(ge=0)] = None
    timeout_secs: Annotated[int | None, Field(ge=0)] = None


class Type30(Enum):
    base64 = 'base64'


class ImageSource1(BaseModel):
    data: str
    media_type: str
    type: Type30


class Type31(Enum):
    url = 'url'


class ImageSource2(BaseModel):
    type: Type31
    url: str


class ImageUrl(BaseModel):
    detail: str | None = None
    url: str


class IncludeField(Enum):
    code_interpreter_call_outputs = 'code_interpreter_call.outputs'
    computer_call_output_output_image_url = 'computer_call_output.output.image_url'
    file_search_call_results = 'file_search_call.results'
    message_input_image_image_url = 'message.input_image.image_url'
    message_output_text_logprobs = 'message.output_text.logprobs'
    reasoning_encrypted_content = 'reasoning.encrypted_content'


class Type32(Enum):
    text = 'text'


class InputContentBlock1(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    citations: Annotated[
        list[Citation1 | Citation2 | Citation3 | Citation4 | Citation5] | None,
        Field(description='Citations for this text block'),
    ] = None
    text: Annotated[str, Field(description='The text content')]
    type: Type32


class Type33(Enum):
    image = 'image'


class InputContentBlock2(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    source: Annotated[
        ImageSource1 | ImageSource2, Field(description='The image source')
    ]
    type: Type33


class Type34(Enum):
    document = 'document'


class Type35(Enum):
    tool_use = 'tool_use'


class InputContentBlock4(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    id: Annotated[str, Field(description='Unique identifier for this tool use')]
    input: Annotated[Any, Field(description='Input arguments for the tool')]
    name: Annotated[str, Field(description='Name of the tool being used')]
    type: Type35


class Type36(Enum):
    tool_result = 'tool_result'


class Type37(Enum):
    thinking = 'thinking'


class InputContentBlock6(BaseModel):
    signature: Annotated[str, Field(description='Signature for the thinking block')]
    thinking: Annotated[str, Field(description='The thinking content')]
    type: Type37


class Type38(Enum):
    redacted_thinking = 'redacted_thinking'


class InputContentBlock7(BaseModel):
    data: Annotated[str, Field(description='The encrypted/redacted data')]
    type: Type38


class Type39(Enum):
    server_tool_use = 'server_tool_use'


class InputContentBlock8(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    id: Annotated[str, Field(description='Unique identifier for this tool use')]
    input: Annotated[Any, Field(description='Input arguments for the tool')]
    name: Annotated[str, Field(description='Name of the server tool')]
    type: Type39


class Type40(Enum):
    search_result = 'search_result'


class Type41(Enum):
    web_search_tool_result = 'web_search_tool_result'


class Type42(Enum):
    tool_search_tool_result = 'tool_search_tool_result'


class InputContentBlock12(BaseModel):
    description: Annotated[str | None, Field(description='Tool description')] = None
    tool_name: Annotated[str, Field(description='Tool name')]
    type: str


class InputSchema(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    properties: dict[str, Any] | None = None
    required: list[str] | None = None
    type: str


class InputTokensDetails(BaseModel):
    cached_tokens: Annotated[int, Field(ge=0)]


class JobStatus(BaseModel):
    job_type: str
    message: str | None = None
    status: str
    timestamp: Annotated[int, Field(ge=0)]
    worker_url: str


class JsonSchemaFormat(BaseModel):
    name: str
    schema_: Annotated[Any, Field(alias='schema')]
    strict: bool | None = None


class TextOffsetItem(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class LogProbs(BaseModel):
    text_offset: list[TextOffsetItem]
    token_logprobs: list[float | None]
    tokens: list[str]
    top_logprobs: list[dict[str, Any] | None]


class McpToolConfig(BaseModel):
    defer_loading: Annotated[
        bool | None, Field(description='Whether to defer loading')
    ] = None
    enabled: Annotated[
        bool | None, Field(description='Whether this tool is enabled')
    ] = None


class McpToolConfiguration(BaseModel):
    allowed_tools: Annotated[
        list[str] | None, Field(description='Allowed tool names')
    ] = None
    enabled: Annotated[bool | None, Field(description='Whether to allow all tools')] = (
        None
    )


class McpToolDefaultConfig(BaseModel):
    defer_loading: Annotated[
        bool | None, Field(description='Whether to defer loading')
    ] = None
    enabled: Annotated[bool | None, Field(description='Whether tools are enabled')] = (
        None
    )


class McpToolInfo(BaseModel):
    annotations: Any | None = None
    description: str | None = None
    input_schema: Any
    name: str


class McpToolset(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this toolset')
    ] = None
    configs: Annotated[
        dict[str, Any] | None,
        Field(description='Configuration overrides for specific tools'),
    ] = None
    default_config: Annotated[
        McpToolDefaultConfig | None,
        Field(
            description='Default configuration applied to all tools from this server'
        ),
    ] = None
    mcp_server_name: Annotated[
        str, Field(description='Name of the MCP server to configure tools for')
    ]
    type: str


class Type43(Enum):
    message_start = 'message_start'


class Type44(Enum):
    message_delta = 'message_delta'


class Type45(Enum):
    message_stop = 'message_stop'


class MessageStreamEvent3(BaseModel):
    type: Type45


class Type46(Enum):
    content_block_start = 'content_block_start'


class Type47(Enum):
    content_block_delta = 'content_block_delta'


class MessageStreamEvent5(BaseModel):
    delta: Annotated[
        ContentBlockDelta1
        | ContentBlockDelta2
        | ContentBlockDelta3
        | ContentBlockDelta4
        | ContentBlockDelta5,
        Field(description='Content block delta for streaming updates'),
    ]
    index: Annotated[int, Field(ge=0)]
    type: Type47


class Type48(Enum):
    content_block_stop = 'content_block_stop'


class MessageStreamEvent6(BaseModel):
    index: Annotated[int, Field(ge=0)]
    type: Type48


class Type49(Enum):
    ping = 'ping'


class MessageStreamEvent7(BaseModel):
    type: Type49


class Type50(Enum):
    error = 'error'


class MessagesErrorResponse(BaseModel):
    message: str
    type: str


class Type51(Enum):
    auto = 'auto'


class MessagesToolChoice1(BaseModel):
    disable_parallel_tool_use: bool | None = None
    type: Type51


class Type52(Enum):
    any = 'any'


class MessagesToolChoice2(BaseModel):
    disable_parallel_tool_use: bool | None = None
    type: Type52


class Type53(Enum):
    tool = 'tool'


class MessagesToolChoice3(BaseModel):
    disable_parallel_tool_use: bool | None = None
    name: str
    type: Type53


class Type54(Enum):
    none = 'none'


class MessagesToolChoice4(BaseModel):
    type: Type54


class Metadata(BaseModel):
    user_id: Annotated[
        str | None,
        Field(
            description='An external identifier for the user who is associated with the request.'
        ),
    ] = None


class ModelInfo(BaseModel):
    created_at: Annotated[str, Field(description='When the model was created')]
    display_name: Annotated[str, Field(description='Display name')]
    id: Annotated[str, Field(description='Model ID')]
    type: Annotated[str, Field(description='Object type (always "model")')]


class ModelTypeEnum(Enum):
    chat = 'chat'
    completions = 'completions'
    responses = 'responses'
    embeddings = 'embeddings'
    rerank = 'rerank'
    generate = 'generate'
    vision = 'vision'
    tools = 'tools'
    reasoning = 'reasoning'
    image_gen = 'image_gen'
    audio = 'audio'
    moderation = 'moderation'


class OutputTokensDetails(BaseModel):
    reasoning_tokens: Annotated[int, Field(ge=0)]


class ParseFunctionCallResponse(BaseModel):
    remaining_text: Annotated[
        str, Field(description='Remaining text after extracting function calls.')
    ]
    success: Annotated[bool, Field(description='Whether parsing succeeded.')]
    tool_calls: Annotated[list[Any], Field(description='Extracted tool calls.')]


class PromptTokenUsageInfo(BaseModel):
    cached_tokens: Annotated[int, Field(ge=0)]


class ProviderType1(Enum):
    openai = 'openai'


class ProviderType2(Enum):
    xai = 'xai'


class ProviderType3(Enum):
    anthropic = 'anthropic'


class ProviderType4(Enum):
    gemini = 'gemini'


class ProviderType5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    custom: str


class ReasoningEffort(Enum):
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'


class ReasoningInfo(BaseModel):
    effort: str | None = None
    summary: str | None = None


class ReasoningSummary(Enum):
    auto = 'auto'
    concise = 'concise'
    detailed = 'detailed'


class RequireApproval(Enum):
    always = 'always'
    never = 'never'


class RerankResult(BaseModel):
    document: Annotated[
        str | None,
        Field(description='The document text (if return_documents was true)'),
    ] = None
    index: Annotated[
        int, Field(description='Original index of the document in the request', ge=0)
    ]
    meta_info: Annotated[
        dict[str, Any] | None,
        Field(description='Additional metadata about the ranking'),
    ] = None
    score: Annotated[float, Field(description='Relevance score for the document')]


class Type55(Enum):
    output_text = 'output_text'


class Type56(Enum):
    input_text = 'input_text'


class ResponseContentPart2(BaseModel):
    text: str
    type: Type56


class Type57(Enum):
    unknown = 'unknown'


class ResponseContentPart3(BaseModel):
    type: Type57


class Type58(Enum):
    text = 'text'


class ResponseFormat1(BaseModel):
    type: Type58


class Type59(Enum):
    json_object = 'json_object'


class ResponseFormat2(BaseModel):
    type: Type59


class Type60(Enum):
    json_schema = 'json_schema'


class ResponseFormat3(BaseModel):
    json_schema: JsonSchemaFormat
    type: Type60


class Type61(Enum):
    message = 'message'


class Type62(Enum):
    reasoning = 'reasoning'


class Type63(Enum):
    function_call = 'function_call'


class ResponseInputOutputItem3(BaseModel):
    arguments: str
    call_id: str
    id: str
    name: str
    output: str | None = None
    status: str | None = None
    type: Type63


class Type64(Enum):
    function_call_output = 'function_call_output'


class ResponseInputOutputItem4(BaseModel):
    call_id: str
    id: str | None = None
    output: str
    status: str | None = None
    type: Type64


class Type65(Enum):
    mcp_approval_request = 'mcp_approval_request'


class ResponseInputOutputItem5(BaseModel):
    arguments: str
    id: str
    name: str
    server_label: str
    type: Type65


class Type66(Enum):
    mcp_approval_response = 'mcp_approval_response'


class ResponseInputOutputItem6(BaseModel):
    approval_request_id: str
    approve: bool
    id: str | None = None
    reason: str | None = None
    type: Type66


class Type67(Enum):
    message = 'message'


class Type68(Enum):
    reasoning = 'reasoning'


class Type69(Enum):
    function_call = 'function_call'


class ResponseOutputItem3(BaseModel):
    arguments: str
    call_id: str
    id: str
    name: str
    output: str | None = None
    status: str
    type: Type69


class Type70(Enum):
    mcp_list_tools = 'mcp_list_tools'


class ResponseOutputItem4(BaseModel):
    id: str
    server_label: str
    tools: list[McpToolInfo]
    type: Type70


class Type71(Enum):
    mcp_call = 'mcp_call'


class ResponseOutputItem5(BaseModel):
    approval_request_id: str | None = None
    arguments: str
    error: str | None = None
    id: str
    name: str
    output: str
    server_label: str
    status: str
    type: Type71


class Type72(Enum):
    mcp_approval_request = 'mcp_approval_request'


class ResponseOutputItem6(BaseModel):
    arguments: str
    id: str
    name: str
    server_label: str
    type: Type72


class Type73(Enum):
    web_search_call = 'web_search_call'


class Type74(Enum):
    code_interpreter_call = 'code_interpreter_call'


class ResponseOutputItem8(BaseModel):
    code: str | None = None
    container_id: str
    id: str
    outputs: list[CodeInterpreterOutput1 | CodeInterpreterOutput2] | None = None
    status: CodeInterpreterCallStatus
    type: Type74


class Type75(Enum):
    file_search_call = 'file_search_call'


class ResponseOutputItem9(BaseModel):
    id: str
    queries: list[str]
    results: list[FileSearchResult] | None = None
    status: FileSearchCallStatus
    type: Type75


class Type76(Enum):
    reasoning_text = 'reasoning_text'


class ResponseReasoningContent1(BaseModel):
    text: str
    type: Type76


class ResponseReasoningContent(RootModel[ResponseReasoningContent1]):
    root: ResponseReasoningContent1


class ResponseReasoningParam(BaseModel):
    effort: ReasoningEffort | None = 'medium'
    summary: ReasoningSummary | None = None


class ResponseStatus(Enum):
    queued = 'queued'
    in_progress = 'in_progress'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class Type77(Enum):
    function = 'function'


class ResponseTool1(BaseModel):
    description: str | None = None
    name: str
    parameters: Any
    strict: Annotated[
        bool | None,
        Field(
            description='Whether to enable strict schema adherence (OpenAI structured outputs)'
        ),
    ] = None
    type: Type77


class Type78(Enum):
    web_search_preview = 'web_search_preview'


class ResponseTool2(BaseModel):
    search_context_size: str | None = None
    type: Type78
    user_location: Any | None = None


class Type79(Enum):
    code_interpreter = 'code_interpreter'


class ResponseTool3(BaseModel):
    container: Any | None = None
    type: Type79


class Type80(Enum):
    mcp = 'mcp'


class ResponseTool4(BaseModel):
    allowed_tools: list[str] | None = None
    authorization: str | None = None
    headers: Annotated[
        dict[str, Any] | None,
        Field(
            description='Custom headers to send to MCP server (from request payload, not HTTP headers)'
        ),
    ] = None
    require_approval: Annotated[
        RequireApproval | None,
        Field(description='Approval requirement configuration for MCP tools.'),
    ] = None
    server_description: str | None = None
    server_label: str
    server_url: str | None = None
    type: Type80


class ResponseUsage(BaseModel):
    input_tokens: Annotated[int, Field(ge=0)]
    input_tokens_details: InputTokensDetails | None = None
    output_tokens: Annotated[int, Field(ge=0)]
    output_tokens_details: OutputTokensDetails | None = None
    total_tokens: Annotated[int, Field(ge=0)]


class ResponsesServiceTier(Enum):
    auto = 'auto'
    default = 'default'
    flex = 'flex'
    scale = 'scale'
    priority = 'priority'


class RoleModel(Enum):
    user = 'user'
    assistant = 'assistant'


class RuntimeType1(Enum):
    sglang = 'sglang'


class RuntimeType2(Enum):
    vllm = 'vllm'


class RuntimeType3(Enum):
    trtllm = 'trtllm'


class RuntimeType4(Enum):
    external = 'external'


class SeparateReasoningRequest(BaseModel):
    reasoning_parser: Annotated[
        str,
        Field(
            description='The parser type/name to use for reasoning detection (e.g., "step3", "deepseek_r1").'
        ),
    ]
    text: Annotated[str, Field(description='The text to parse for reasoning content.')]


class SeparateReasoningResponse(BaseModel):
    normal_text: Annotated[str, Field(description='Normal (non-reasoning) text.')]
    reasoning_text: Annotated[str, Field(description='Extracted reasoning text.')]
    success: Annotated[bool, Field(description='Whether parsing succeeded.')]


class ServerToolUsage(BaseModel):
    web_search_requests: Annotated[int, Field(ge=0)]


class ServiceTier(Enum):
    auto = 'auto'
    standard_only = 'standard_only'


class StopReason1(Enum):
    end_turn = 'end_turn'


class StopReason2(Enum):
    max_tokens = 'max_tokens'


class StopReason3(Enum):
    stop_sequence = 'stop_sequence'


class StopReason4(Enum):
    tool_use = 'tool_use'


class StopReason5(Enum):
    pause_turn = 'pause_turn'


class StopReason6(Enum):
    refusal = 'refusal'


class StreamOptions(BaseModel):
    include_usage: bool | None = None


class TextBlock(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    citations: Annotated[
        list[Citation1 | Citation2 | Citation3 | Citation4 | Citation5] | None,
        Field(description='Citations for this text block'),
    ] = None
    text: Annotated[str, Field(description='The text content')]


class TextEditorTool(BaseModel):
    cache_control: CacheControl | None = None
    name: str
    type: str


class Type81(Enum):
    text = 'text'


class TextFormat1(BaseModel):
    type: Type81


class Type82(Enum):
    json_object = 'json_object'


class TextFormat2(BaseModel):
    type: Type82


class Type83(Enum):
    json_schema = 'json_schema'


class TextFormat3(BaseModel):
    description: str | None = None
    name: str
    schema_: Annotated[Any, Field(alias='schema')]
    strict: bool | None = None
    type: Type83


class Type84(Enum):
    enabled = 'enabled'


class ThinkingConfig1(BaseModel):
    budget_tokens: Annotated[
        int, Field(description='Budget in tokens for thinking (minimum 1024)', ge=0)
    ]
    type: Type84


class Type85(Enum):
    disabled = 'disabled'


class ThinkingConfig2(BaseModel):
    type: Type85


class TokensInputItem(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class TokensResultItem(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class Tool(BaseModel):
    function: Function
    type: str


class ToolCall(BaseModel):
    function: FunctionCallResponse
    id: str
    type: str


class ToolCallDelta(BaseModel):
    function: FunctionCallDelta | None = None
    id: str | None = None
    index: Annotated[int, Field(ge=0)]
    type: str | None = None


class ToolChoice1(BaseModel):
    function: FunctionChoice
    type: str


class ToolChoiceValue(Enum):
    auto = 'auto'
    required = 'required'
    none = 'none'


class Type86(Enum):
    function = 'function'


class ToolReference1(BaseModel):
    name: str
    type: Type86


class Type87(Enum):
    mcp = 'mcp'


class ToolReference2(BaseModel):
    name: str | None = None
    server_label: str
    type: Type87


class Type88(Enum):
    file_search = 'file_search'


class ToolReference3(BaseModel):
    type: Type88


class Type89(Enum):
    web_search_preview = 'web_search_preview'


class ToolReference4(BaseModel):
    type: Type89


class Type90(Enum):
    computer_use_preview = 'computer_use_preview'


class ToolReference5(BaseModel):
    type: Type90


class Type91(Enum):
    code_interpreter = 'code_interpreter'


class ToolReference6(BaseModel):
    type: Type91


class Type92(Enum):
    image_generation = 'image_generation'


class ToolReference7(BaseModel):
    type: Type92


class ToolReferenceBlock(BaseModel):
    description: Annotated[str | None, Field(description='Tool description')] = None
    tool_name: Annotated[str, Field(description='Tool name')]
    type: str


class Type93(Enum):
    text = 'text'


class ToolResultContentBlock1(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    citations: Annotated[
        list[Citation1 | Citation2 | Citation3 | Citation4 | Citation5] | None,
        Field(description='Citations for this text block'),
    ] = None
    text: Annotated[str, Field(description='The text content')]
    type: Type93


class Type94(Enum):
    image = 'image'


class ToolResultContentBlock2(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    source: Annotated[
        ImageSource1 | ImageSource2, Field(description='The image source')
    ]
    type: Type94


class Type95(Enum):
    document = 'document'


class Type96(Enum):
    search_result = 'search_result'


class ToolResultContentBlock4(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    citations: Annotated[
        CitationsConfig | None, Field(description='Citations configuration')
    ] = None
    content: Annotated[
        list[TextBlock], Field(description='Content of the search result')
    ]
    source: Annotated[str, Field(description='Source URL or identifier')]
    title: Annotated[str, Field(description='Title of the search result')]
    type: Type96


class ToolSearchResultContent(BaseModel):
    tool_references: Annotated[
        list[ToolReferenceBlock],
        Field(description='Tool references found by the search'),
    ]
    type: str


class ToolSearchTool(BaseModel):
    allowed_callers: Annotated[
        list[str] | None, Field(description='Allowed callers for this tool')
    ] = None
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this tool')
    ] = None
    name: str
    type: str


class TopLogProb(BaseModel):
    bytes: list[Byte] | None = None
    logprob: float
    token: str


class Truncation(Enum):
    auto = 'auto'
    disabled = 'disabled'


class Usage(BaseModel):
    completion_tokens: Annotated[int, Field(ge=0)]
    completion_tokens_details: CompletionTokensDetails | None = None
    prompt_tokens: Annotated[int, Field(ge=0)]
    total_tokens: Annotated[int, Field(ge=0)]


class UsageInfo(BaseModel):
    completion_tokens: Annotated[int, Field(ge=0)]
    prompt_tokens: Annotated[int, Field(ge=0)]
    prompt_tokens_details: PromptTokenUsageInfo | None = None
    reasoning_tokens: Annotated[int | None, Field(ge=0)] = None
    total_tokens: Annotated[int, Field(ge=0)]


class UserLocation(BaseModel):
    city: str | None = None
    country: str | None = None
    region: str | None = None
    timezone: str | None = None
    type: str


class VideoUrl(BaseModel):
    url: str


class Type97(Enum):
    search = 'search'


class Type98(Enum):
    open_page = 'open_page'


class WebSearchAction2(BaseModel):
    type: Type98
    url: str


class Type99(Enum):
    find = 'find'


class WebSearchAction3(BaseModel):
    pattern: str
    type: Type99
    url: str


class WebSearchCallStatus(Enum):
    in_progress = 'in_progress'
    searching = 'searching'
    completed = 'completed'
    failed = 'failed'


class WebSearchResultBlock(BaseModel):
    encrypted_content: Annotated[str, Field(description='Encrypted content')]
    page_age: Annotated[str | None, Field(description='Page age (if available)')] = None
    title: Annotated[str, Field(description='Title of the search result')]
    url: Annotated[str, Field(description='URL of the search result')]


class WebSearchSource(BaseModel):
    type: str
    url: str


class WebSearchTool(BaseModel):
    allowed_domains: list[str] | None = None
    blocked_domains: list[str] | None = None
    cache_control: CacheControl | None = None
    max_uses: Annotated[int | None, Field(ge=0)] = None
    name: str
    type: str
    user_location: UserLocation | None = None


class WebSearchToolResultErrorCode(Enum):
    invalid_tool_input = 'invalid_tool_input'
    unavailable = 'unavailable'
    max_uses_exceeded = 'max_uses_exceeded'
    too_many_requests = 'too_many_requests'
    query_too_long = 'query_too_long'


class WorkerType1(Enum):
    regular = 'regular'


class WorkerType2(Enum):
    prefill = 'prefill'


class WorkerType3(Enum):
    decode = 'decode'


class WorkerUpdateRequest(BaseModel):
    api_key: Annotated[
        str | None, Field(description='Update API key (for key rotation)')
    ] = None
    cost: Annotated[float | None, Field(description='Update cost')] = None
    health: Annotated[
        HealthCheckUpdate | None,
        Field(
            description='Update health check configuration (partial — only specified fields change)'
        ),
    ] = None
    labels: Annotated[dict[str, Any] | None, Field(description='Update labels')] = None
    priority: Annotated[int | None, Field(description='Update priority', ge=0)] = None


class BashTool(BaseModel):
    cache_control: CacheControl | None = None
    name: str
    type: str


class ChatCompletionMessage(BaseModel):
    content: str | None = None
    reasoning_content: str | None = None
    role: str
    tool_calls: list[ToolCall] | None = None


class ChatLogProbsContent(BaseModel):
    bytes: list[Byte] | None = None
    logprob: float
    token: str
    top_logprobs: list[TopLogProb]


class ChatMessageDelta(BaseModel):
    content: str | None = None
    reasoning_content: str | None = None
    role: str | None = None
    tool_calls: list[ToolCallDelta] | None = None


class ClassifyResponse(BaseModel):
    created: Annotated[
        int, Field(description='Unix timestamp (seconds since epoch)', ge=0)
    ]
    data: Annotated[
        list[ClassifyData],
        Field(description='Classification results (one per input in batch)'),
    ]
    id: Annotated[
        str, Field(description='Unique request ID (format: "classify-{uuid}")')
    ]
    model: Annotated[str, Field(description='Model name')]
    object: Annotated[str, Field(description='Always "list"')]
    usage: Annotated[UsageInfo, Field(description='Token usage info')]


class CompletionChoice(BaseModel):
    finish_reason: str | None = None
    index: Annotated[int, Field(ge=0)]
    logprobs: LogProbs | None = None
    matched_stop: Annotated[
        Any | None,
        Field(description='Information about which stop condition was matched'),
    ] = None
    text: str


class CompletionRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    best_of: Annotated[
        int | None,
        Field(
            description='Generates best_of completions server-side and returns the "best"',
            ge=0,
        ),
    ] = None
    ebnf: Annotated[
        str | None, Field(description='EBNF grammar constraint for structured output')
    ] = None
    echo: Annotated[
        bool | None,
        Field(description='Echo back the prompt in addition to the completion'),
    ] = False
    frequency_penalty: Annotated[
        float | None,
        Field(
            description='Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far'
        ),
    ] = None
    ignore_eos: Annotated[
        bool | None,
        Field(description='Ignore end-of-sequence tokens during generation'),
    ] = False
    json_schema: Annotated[
        str | None, Field(description='JSON schema constraint for structured output')
    ] = None
    logit_bias: Annotated[
        dict[str, Any] | None,
        Field(
            description='Modify the likelihood of specified tokens appearing in the completion'
        ),
    ] = None
    logprobs: Annotated[
        int | None,
        Field(
            description='Include the log probabilities on the logprobs most likely tokens',
            ge=0,
        ),
    ] = None
    lora_path: Annotated[
        str | None, Field(description='Path to LoRA adapter(s) for model customization')
    ] = None
    max_tokens: Annotated[
        int | None, Field(description='The maximum number of tokens to generate', ge=0)
    ] = None
    min_p: Annotated[
        float | None, Field(description='Min-p nucleus sampling parameter')
    ] = None
    min_tokens: Annotated[
        int | None, Field(description='Minimum number of tokens to generate', ge=0)
    ] = None
    model: Annotated[
        str,
        Field(
            description='ID of the model to use (required for OpenAI, optional for some implementations, such as SGLang)'
        ),
    ]
    n: Annotated[
        int | None,
        Field(description='How many completions to generate for each prompt', ge=0),
    ] = None
    no_stop_trim: Annotated[
        bool | None, Field(description='Skip trimming stop tokens from output')
    ] = False
    presence_penalty: Annotated[
        float | None,
        Field(
            description='Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far'
        ),
    ] = None
    prompt: Annotated[
        str | list[str], Field(description='The prompt(s) to generate completions for')
    ]
    regex: Annotated[
        str | None, Field(description='Regex constraint for output generation')
    ] = None
    repetition_penalty: Annotated[
        float | None,
        Field(description='Repetition penalty for reducing repetitive text'),
    ] = None
    return_hidden_states: Annotated[
        bool | None, Field(description='Return model hidden states')
    ] = False
    sampling_seed: Annotated[
        int | None, Field(description='Sampling seed for deterministic outputs', ge=0)
    ] = None
    seed: Annotated[
        int | None,
        Field(
            description='If specified, our system will make a best effort to sample deterministically'
        ),
    ] = None
    session_params: Annotated[
        dict[str, Any] | None,
        Field(description='Session parameters for continual prompting'),
    ] = None
    skip_special_tokens: Annotated[
        bool | None, Field(description='Skip special tokens during detokenization')
    ] = True
    stop: Annotated[
        str | list[str] | None,
        Field(
            description='Up to 4 sequences where the API will stop generating further tokens'
        ),
    ] = None
    stop_token_ids: Annotated[
        list[StopTokenId] | None,
        Field(description='Specific token IDs to use as stop conditions'),
    ] = None
    stream: Annotated[
        bool | None, Field(description='Whether to stream back partial progress')
    ] = False
    stream_options: Annotated[
        StreamOptions | None, Field(description='Options for streaming response')
    ] = None
    suffix: Annotated[
        str | None,
        Field(description='The suffix that comes after a completion of inserted text'),
    ] = None
    temperature: Annotated[
        float | None,
        Field(description='What sampling temperature to use, between 0 and 2'),
    ] = None
    top_k: Annotated[
        int | None, Field(description='Top-k sampling parameter (-1 to disable)')
    ] = None
    top_p: Annotated[
        float | None,
        Field(
            description='An alternative to sampling with temperature (nucleus sampling)'
        ),
    ] = None
    user: Annotated[
        str | None, Field(description='A unique identifier representing your end-user')
    ] = None


class CompletionResponse(BaseModel):
    choices: list[CompletionChoice]
    created: Annotated[int, Field(ge=0)]
    id: str
    model: str
    object: str
    system_fingerprint: str | None = None
    usage: Usage | None = None


class CompletionStreamChoice(BaseModel):
    finish_reason: str | None = None
    index: Annotated[int, Field(ge=0)]
    logprobs: LogProbs | None = None
    text: str


class CompletionStreamResponse(BaseModel):
    choices: list[CompletionStreamChoice]
    created: Annotated[int, Field(ge=0)]
    id: str
    model: str
    object: str
    system_fingerprint: str | None = None


class ContentBlock7(BaseModel):
    content: ToolSearchResultContent
    tool_use_id: str
    type: Type14


class ContentPart2(BaseModel):
    image_url: ImageUrl
    type: Type24


class ContentPart3(BaseModel):
    type: Type25
    video_url: VideoUrl


class CustomTool(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this tool')
    ] = None
    defer_loading: Annotated[
        bool | None, Field(description='Whether to defer loading this tool')
    ] = None
    description: Annotated[
        str | None, Field(description='Description of what this tool does')
    ] = None
    input_schema: Annotated[
        InputSchema, Field(description="JSON schema for the tool's input")
    ]
    name: Annotated[str, Field(description='Name of the tool')]
    type: Annotated[
        str | None, Field(description='Optional type (defaults to "custom")')
    ] = None


class DetokenizeRequest(BaseModel):
    model: Annotated[
        str | None, Field(description='Model name for tokenizer selection')
    ] = 'unknown'
    skip_special_tokens: Annotated[
        bool | None,
        Field(
            description='Whether to skip special tokens (e.g., padding or EOS) during decoding'
        ),
    ] = True
    tokens: Annotated[
        list[TokensInputItem] | list[list[TokensInputItem]],
        Field(
            description='Token IDs to detokenize - single list or batch (list of lists)'
        ),
    ]


class DetokenizeResponse(BaseModel):
    text: Annotated[
        str | list[str],
        Field(
            description='Decoded text - single string for single input, list for batch'
        ),
    ]


class EmbeddingResponse(BaseModel):
    data: list[EmbeddingObject]
    model: str
    object: str
    usage: UsageInfo


class GenerateFinishReason1(BaseModel):
    length: Annotated[int, Field(ge=0)]
    type: GenerateFinishType


class GenerateFinishReason2(BaseModel):
    type: GenerateFinishType


class GenerateMetaInfo(BaseModel):
    cached_tokens: Annotated[int, Field(ge=0)]
    completion_tokens: Annotated[int, Field(ge=0)]
    e2e_latency: float
    finish_reason: Annotated[
        GenerateFinishReason1 | GenerateFinishReason2 | Any,
        Field(description='Finish reason for generate endpoint'),
    ]
    id: str
    input_token_logprobs: list[list[float | None]] | None = None
    matched_stop: Any | None = None
    output_token_logprobs: list[list[float | None]] | None = None
    prompt_tokens: Annotated[int, Field(ge=0)]
    weight_version: str


class GenerateResponse(BaseModel):
    meta_info: GenerateMetaInfo
    output_ids: list[OutputId]
    text: str


class InputContentBlock9(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    citations: Annotated[
        CitationsConfig | None, Field(description='Citations configuration')
    ] = None
    content: Annotated[
        list[TextBlock], Field(description='Content of the search result')
    ]
    source: Annotated[str, Field(description='Source URL or identifier')]
    title: Annotated[str, Field(description='Title of the search result')]
    type: Type40


class InputContentBlock11(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    content: Annotated[ToolSearchResultContent, Field(description='The search results')]
    tool_use_id: Annotated[
        str, Field(description='The ID of the tool use this is a result for')
    ]
    type: Type42


class ListModelsResponse(BaseModel):
    data: list[ModelInfo]
    first_id: str | None = None
    has_more: bool
    last_id: str | None = None


class McpServerConfig(BaseModel):
    authorization_token: Annotated[
        str | None, Field(description='Authorization token (if required)')
    ] = None
    name: Annotated[str, Field(description='Name of the MCP server')]
    tool_configuration: Annotated[
        McpToolConfiguration | None,
        Field(description='Tool configuration for this server'),
    ] = None
    type: Annotated[str | None, Field(description='Server type (always "url")')] = 'url'
    url: Annotated[str, Field(description='MCP server URL')]


class MessageDelta(BaseModel):
    stop_reason: (
        StopReason1
        | StopReason2
        | StopReason3
        | StopReason4
        | StopReason5
        | StopReason6
        | None
    ) = None
    stop_sequence: str | None = None


class MessageDeltaUsage(BaseModel):
    cache_creation_input_tokens: Annotated[int | None, Field(ge=0)] = None
    cache_read_input_tokens: Annotated[int | None, Field(ge=0)] = None
    input_tokens: Annotated[int | None, Field(ge=0)] = None
    output_tokens: Annotated[int, Field(ge=0)]
    server_tool_use: ServerToolUsage | None = None


class MessageStreamEvent2(BaseModel):
    delta: MessageDelta
    type: Type44
    usage: MessageDeltaUsage


class MessageStreamEvent8(BaseModel):
    error: MessagesErrorResponse
    type: Type50


class MessagesUsage(BaseModel):
    cache_creation: Annotated[
        CacheCreation | None, Field(description='Breakdown of cached tokens by TTL')
    ] = None
    cache_creation_input_tokens: Annotated[
        int | None,
        Field(
            description='The number of input tokens used to create the cache entry',
            ge=0,
        ),
    ] = None
    cache_read_input_tokens: Annotated[
        int | None,
        Field(description='The number of input tokens read from the cache', ge=0),
    ] = None
    input_tokens: Annotated[
        int, Field(description='The number of input tokens used', ge=0)
    ]
    output_tokens: Annotated[
        int, Field(description='The number of output tokens used', ge=0)
    ]
    server_tool_use: Annotated[
        ServerToolUsage | None, Field(description='Server tool usage information')
    ] = None
    service_tier: Annotated[
        str | None, Field(description='Service tier used for the request')
    ] = None


class ModelCard(BaseModel):
    aliases: Annotated[
        list[str] | None, Field(description='Alternative names/aliases for this model')
    ] = None
    architectures: Annotated[
        list[str] | None,
        Field(
            description='Model architectures from HuggingFace config (e.g., ["LlamaForCausalLM"])'
        ),
    ] = None
    chat_template: Annotated[
        str | None, Field(description='Chat template (Jinja2 template string or path)')
    ] = None
    context_length: Annotated[
        int | None, Field(description='Maximum context length in tokens', ge=0)
    ] = None
    display_name: Annotated[
        str | None,
        Field(description='Optional display name (e.g., "Llama 3.1 8B Instruct")'),
    ] = None
    hf_model_type: Annotated[
        str | None,
        Field(
            description='HuggingFace model type string (e.g., "llama", "qwen2", "gpt-oss")'
        ),
    ] = None
    id: Annotated[
        str,
        Field(
            description='Primary model ID (e.g., "meta-llama/Llama-3.1-8B-Instruct")'
        ),
    ]
    id2label: Annotated[
        dict[str, str] | None,
        Field(
            description='Classification label mapping (class index -> label name). Empty if not a classification model.'
        ),
    ] = None
    metadata: Annotated[
        Any | None,
        Field(description='User-defined metadata (for fields not covered above)'),
    ] = None
    model_type: Annotated[
        list[ModelTypeEnum] | None,
        Field(description='Supported endpoint types (bitflags)'),
    ] = ['chat', 'completions', 'responses', 'tools']
    num_labels: Annotated[
        int | None,
        Field(
            description='Number of classification labels (0 if not a classifier).', ge=0
        ),
    ] = None
    provider: Annotated[
        ProviderType1
        | ProviderType2
        | ProviderType3
        | ProviderType4
        | ProviderType5
        | None,
        Field(
            description='Provider hint for API transformations. `None` means native/passthrough (no transformation needed).'
        ),
    ] = None
    reasoning_parser: Annotated[
        str | None,
        Field(description='Reasoning parser type (e.g., "deepseek", "qwen")'),
    ] = None
    tokenizer_path: Annotated[
        str | None,
        Field(
            description='Path to tokenizer (e.g., HuggingFace model ID or local path)'
        ),
    ] = None
    tool_parser: Annotated[
        str | None,
        Field(
            description='Tool/function calling parser type (e.g., "llama", "mistral")'
        ),
    ] = None


class ParseFunctionCallRequest(BaseModel):
    text: Annotated[str, Field(description='The text to parse for function calls.')]
    tool_call_parser: Annotated[
        str,
        Field(
            description='The parser type/name to use for parsing (e.g., "json", "pythonic").'
        ),
    ]
    tools: Annotated[
        list[Tool],
        Field(description='The list of available tools that the model can call.'),
    ]


class RerankRequest(BaseModel):
    documents: Annotated[list[str], Field(description='List of documents to be ranked')]
    model: Annotated[str | None, Field(description='Model to use for reranking')] = (
        'unknown'
    )
    query: Annotated[str, Field(description='The query text to rank documents against')]
    return_documents: Annotated[
        bool | None,
        Field(description='Whether to return documents in addition to scores'),
    ] = True
    rid: Annotated[
        str | list[str] | None, Field(description='Request ID for tracking')
    ] = None
    top_k: Annotated[
        int | None,
        Field(description='Maximum number of documents to return (optional)', ge=1),
    ] = None
    user: Annotated[str | None, Field(description='User identifier')] = None


class RerankResponse(BaseModel):
    created: Annotated[int, Field(description='Creation timestamp')]
    id: Annotated[str | list[str] | None, Field(description='Response ID')] = None
    model: Annotated[str, Field(description='Model used for reranking')]
    object: Annotated[str | None, Field(description='Response object type')] = 'rerank'
    results: Annotated[
        list[RerankResult],
        Field(description='Ranked results sorted by score (highest first)'),
    ]
    usage: Annotated[UsageInfo | None, Field(description='Usage information')] = None


class ResponseInputOutputItem2(BaseModel):
    content: list[ResponseReasoningContent] | None = None
    id: str
    status: str | None = None
    summary: list[str]
    type: Type62


class ResponseOutputItem2(BaseModel):
    content: list[ResponseReasoningContent]
    id: str
    status: str | None = None
    summary: list[str]
    type: Type68


class SamplingParams(BaseModel):
    ebnf: str | None = None
    frequency_penalty: Annotated[float | None, Field(ge=-2.0, le=2.0)] = None
    ignore_eos: bool | None = None
    json_schema: str | None = None
    max_new_tokens: Annotated[
        int | None,
        Field(
            description='Maximum number of new tokens to generate (must be >= 0)', ge=0
        ),
    ] = None
    min_new_tokens: Annotated[
        int | None,
        Field(
            description='Minimum number of new tokens (validated in schema function for cross-field check with max_new_tokens)',
            ge=0,
        ),
    ] = None
    min_p: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    n: Annotated[int | None, Field(ge=0)] = None
    no_stop_trim: bool | None = None
    presence_penalty: Annotated[float | None, Field(ge=-2.0, le=2.0)] = None
    regex: str | None = None
    repetition_penalty: Annotated[float | None, Field(ge=0.0, le=2.0)] = None
    sampling_seed: Annotated[int | None, Field(ge=0)] = None
    skip_special_tokens: bool | None = None
    stop: str | list[str] | None = None
    stop_token_ids: list[StopTokenId] | None = None
    temperature: Annotated[
        float | None,
        Field(
            description='Temperature for sampling (must be >= 0.0, no upper limit)',
            ge=0.0,
        ),
    ] = None
    top_k: Annotated[
        int | None, Field(description='Top-k sampling (-1 to disable, or >= 1)')
    ] = None
    top_p: Annotated[
        float | None, Field(description='Top-p nucleus sampling (0.0 < top_p <= 1.0)')
    ] = None


class TextConfig(BaseModel):
    format: TextFormat1 | TextFormat2 | TextFormat3 | None = None


class TokenizeRequest(BaseModel):
    model: Annotated[
        str | None, Field(description='Model name for tokenizer selection')
    ] = 'unknown'
    prompt: Annotated[
        str | list[str],
        Field(
            description='Text(s) to tokenize - can be a single string or array of strings'
        ),
    ]


class TokenizeResponse(BaseModel):
    char_count: Annotated[
        int | list[int],
        Field(
            description='Character count(s) of input - single int for single input, list for batch'
        ),
    ]
    count: Annotated[
        int | list[int],
        Field(
            description='Token count(s) - single int for single input, list for batch'
        ),
    ]
    tokens: Annotated[
        list[TokensResultItem] | list[list[TokensResultItem]],
        Field(
            description='Token IDs - single list for single input, nested list for batch'
        ),
    ]


class ToolChoice2(BaseModel):
    mode: str
    tools: list[
        ToolReference1
        | ToolReference2
        | ToolReference3
        | ToolReference4
        | ToolReference5
        | ToolReference6
        | ToolReference7
    ]
    type: str


class WebSearchAction1(BaseModel):
    queries: list[str] | None = None
    query: str | None = None
    sources: list[WebSearchSource] | None = None
    type: Type97


class WebSearchToolResultError(BaseModel):
    error_code: WebSearchToolResultErrorCode
    type: str


class WorkerSpec(BaseModel):
    api_key: Annotated[
        str | None,
        Field(
            description='Worker API key. Accepted on input, never included in responses.'
        ),
    ] = None
    bootstrap_port: Annotated[
        int | None,
        Field(
            description='Bootstrap port for prefill workers in PD disaggregated mode.',
            ge=0,
        ),
    ] = None
    connection_mode: Annotated[
        ConnectionMode1 | ConnectionMode2 | None,
        Field(description='Connection mode: http or grpc.'),
    ] = 'http'
    cost: Annotated[
        float | None, Field(description='Worker cost factor (baseline = 1.0).')
    ] = 1.0
    dp_base_url: Annotated[
        str | None,
        Field(
            description='Base URL without DP rank suffix (for DP-aware workers). When set, `url` contains the rank-suffixed form (`{base}@{rank}`).'
        ),
    ] = None
    dp_rank: Annotated[
        int | None, Field(description='Data-parallel rank (None = not DP-aware).', ge=0)
    ] = None
    dp_size: Annotated[
        int | None,
        Field(
            description='Total data-parallel group size (None = not DP-aware).', ge=0
        ),
    ] = None
    health: Annotated[
        HealthCheckUpdate | None,
        Field(
            description='Per-worker health check overrides (partial — only `Some` fields override router defaults).'
        ),
    ] = None
    kv_connector: Annotated[
        str | None,
        Field(
            description='KV connector type (e.g. "MooncakeConnector", "NixlConnector").'
        ),
    ] = None
    kv_role: Annotated[
        str | None,
        Field(description='KV role (e.g. "kv_producer", "kv_consumer", "kv_both").'),
    ] = None
    labels: Annotated[
        dict[str, str] | None, Field(description='Additional labels/tags.')
    ] = None
    load_monitor_interval_secs: Annotated[
        int | None,
        Field(
            description='Per-worker load monitor interval override (seconds). When set, workers in the same group use this interval for load polling. Falls back to the global `load_monitor_interval_secs` from router config.',
            ge=0,
        ),
    ] = None
    max_connection_attempts: Annotated[
        int | None,
        Field(
            description='Maximum connection attempts during worker registration (default: 20).',
            ge=0,
        ),
    ] = 20
    models: Annotated[
        list[ModelCard] | None, Field(description='Models this worker can serve.')
    ] = None
    priority: Annotated[
        int | None, Field(description='Worker priority (higher = preferred).', ge=0)
    ] = 50
    provider: Annotated[
        ProviderType1
        | ProviderType2
        | ProviderType3
        | ProviderType4
        | ProviderType5
        | None,
        Field(
            description='External provider for API transformations. `None` means native/passthrough.'
        ),
    ] = None
    runtime_type: Annotated[
        RuntimeType1 | RuntimeType2 | RuntimeType3 | RuntimeType4 | None,
        Field(description='Runtime type: sglang, vllm, trtllm, or external.'),
    ] = 'sglang'
    url: Annotated[str, Field(description='Worker URL.')]
    worker_type: Annotated[
        WorkerType1 | WorkerType2 | WorkerType3 | None,
        Field(description='Worker type: regular, prefill, or decode.'),
    ] = 'regular'


class ChatLogProbs1(BaseModel):
    content: list[ChatLogProbsContent] | None = None


class ChatMessage1(BaseModel):
    content: str | list[ContentPart1 | ContentPart2 | ContentPart3]
    name: str | None = None
    role: Role


class ChatMessage2(BaseModel):
    content: str | list[ContentPart1 | ContentPart2 | ContentPart3]
    name: str | None = None
    role: Role1


class ChatMessage3(BaseModel):
    content: str | list[ContentPart1 | ContentPart2 | ContentPart3] | None = None
    name: str | None = None
    reasoning_content: Annotated[
        str | None,
        Field(description='Reasoning content for O1-style models (SGLang extension)'),
    ] = None
    role: Role2
    tool_calls: list[ToolCall] | None = None


class ChatMessage4(BaseModel):
    content: str | list[ContentPart1 | ContentPart2 | ContentPart3]
    role: Role3
    tool_call_id: str


class ChatMessage6(BaseModel):
    content: str | list[ContentPart1 | ContentPart2 | ContentPart3]
    name: str | None = None
    role: Role5
    tools: list[Tool] | None = None


class ChatStreamChoice(BaseModel):
    delta: ChatMessageDelta
    finish_reason: str | None = None
    index: Annotated[int, Field(ge=0)]
    logprobs: ChatLogProbs1 | Any | None = None
    matched_stop: Any | None = None


class GenerateRequest(BaseModel):
    audio_data: Annotated[
        Any | None,
        Field(
            description='Audio input data Can be a file name, URL, or base64 encoded string Supports single audio files, lists of audio, or nested lists for batch processing Placeholder for future use'
        ),
    ] = None
    background: Annotated[bool | None, Field(description='Background response')] = False
    bootstrap_host: Annotated[
        str | None, Field(description='For disaggregated inference')
    ] = None
    bootstrap_pair_key: Annotated[
        str | None, Field(description='For disaggregated inference')
    ] = None
    bootstrap_port: Annotated[
        int | None, Field(description='For disaggregated inference')
    ] = None
    bootstrap_room: Annotated[
        int | None, Field(description='For disaggregated inference')
    ] = None
    conversation_id: Annotated[
        str | None, Field(description='Conversation ID for tracking')
    ] = None
    custom_labels: Annotated[
        dict[str, Any] | None, Field(description='Custom metric labels')
    ] = None
    custom_logit_processor: Annotated[
        str | None,
        Field(
            description="Custom logit processor for advanced sampling control. Must be a serialized instance of `CustomLogitProcessor` in python/sglang/srt/sampling/custom_logit_processor.py Use the processor's `to_str()` method to generate the serialized string."
        ),
    ] = None
    data_parallel_rank: Annotated[
        int | None, Field(description='Data parallel rank routing')
    ] = None
    extra_key: Annotated[
        str | None,
        Field(description='Extra key for classifying the request (e.g. cache_salt)'),
    ] = None
    image_data: Annotated[
        Any | None,
        Field(
            description='Image input data Can be an image instance, file name, URL, or base64 encoded string Supports single images, lists of images, or nested lists for batch processing Placeholder for future use'
        ),
    ] = None
    input_embeds: Annotated[
        Any | None,
        Field(
            description='Input embeddings for direct embedding input Can be a 2D array (single request) or 3D array (batch of requests) Placeholder for future use'
        ),
    ] = None
    input_ids: Annotated[
        list[int] | list[list[int]] | None,
        Field(description='Input IDs for tokenized input'),
    ] = None
    log_metrics: Annotated[
        bool | None,
        Field(
            description='Whether to log metrics for this request (e.g. health_generate calls do not log metrics)'
        ),
    ] = True
    logprob_start_len: Annotated[
        int | None,
        Field(
            description='If return logprobs, the start location in the prompt for returning logprobs.'
        ),
    ] = None
    lora_id: Annotated[
        str | None, Field(description='LoRA adapter ID (if pre-loaded)')
    ] = None
    lora_path: Annotated[
        str | None, Field(description='Path to LoRA adapter(s) for model customization')
    ] = None
    modalities: Annotated[
        list[str] | None,
        Field(
            description='The modalities of the image data [image, multi-images, video]'
        ),
    ] = None
    model: str | None = None
    no_logs: Annotated[
        bool | None,
        Field(
            description='Whether to disallow logging for this request (e.g. due to ZDR)'
        ),
    ] = False
    priority: Annotated[int | None, Field(description='Priority for the request')] = (
        None
    )
    return_bytes: Annotated[
        bool | None, Field(description='Whether to return bytes for image generation')
    ] = False
    return_entropy: Annotated[
        bool | None, Field(description='Whether to return entropy')
    ] = False
    return_hidden_states: Annotated[
        bool | None, Field(description='Return model hidden states')
    ] = False
    return_logprob: Annotated[
        bool | None, Field(description='Whether to return logprobs')
    ] = None
    return_text_in_logprobs: Annotated[
        bool | None,
        Field(
            description='Whether to detokenize tokens in text in the returned logprobs.'
        ),
    ] = False
    rid: Annotated[
        str | None,
        Field(description='Request ID for tracking (inherited from BaseReq in Python)'),
    ] = None
    sampling_params: Annotated[
        SamplingParams | None, Field(description='Sampling parameters (sglang style)')
    ] = None
    session_params: Annotated[
        dict[str, Any] | None,
        Field(description='Session parameters for continual prompting'),
    ] = None
    stream: Annotated[
        bool | None, Field(description='Whether to stream the response')
    ] = False
    text: Annotated[
        str | None, Field(description='Text input - SGLang native format')
    ] = None
    token_ids_logprob: Annotated[
        list[TokenIdsLogprobItem] | None,
        Field(description='If return logprobs, the token ids to return logprob for.'),
    ] = None
    top_logprobs_num: Annotated[
        int | None,
        Field(
            description='If return logprobs, the number of top logprobs to return at each position.'
        ),
    ] = None
    video_data: Annotated[
        Any | None,
        Field(
            description='Video input data Can be a file name, URL, or base64 encoded string Supports single videos, lists of videos, or nested lists for batch processing Placeholder for future use'
        ),
    ] = None


class ResponseContentPart1(BaseModel):
    annotations: list[str] | None = None
    logprobs: ChatLogProbs1 | Any | None = None
    text: str
    type: Type55


class ResponseInputOutputItem1(BaseModel):
    content: list[ResponseContentPart1 | ResponseContentPart2 | ResponseContentPart3]
    id: str
    role: str
    status: str | None = None
    type: Type61


class ResponseOutputItem1(BaseModel):
    content: list[ResponseContentPart1 | ResponseContentPart2 | ResponseContentPart3]
    id: str
    role: str
    status: str
    type: Type67


class ResponseOutputItem7(BaseModel):
    action: Annotated[
        WebSearchAction1 | WebSearchAction2 | WebSearchAction3,
        Field(description='Action performed during a web search.'),
    ]
    id: str
    status: WebSearchCallStatus
    type: Type73


class ResponsesResponse(BaseModel):
    created_at: Annotated[int, Field(description='Creation timestamp')]
    error: Annotated[
        Any | None, Field(description='Error information if status is failed')
    ] = None
    id: Annotated[str, Field(description='Response ID')]
    incomplete_details: Annotated[
        Any | None, Field(description='Incomplete details if response was truncated')
    ] = None
    instructions: Annotated[
        str | None, Field(description='System instructions used')
    ] = None
    max_output_tokens: Annotated[
        int | None, Field(description='Max output tokens setting', ge=0)
    ] = None
    metadata: Annotated[
        dict[str, Any] | None, Field(description='Additional metadata')
    ] = {}
    model: Annotated[str, Field(description='Model name')]
    object: Annotated[str | None, Field(description='Object type')] = 'response'
    output: Annotated[
        list[
            ResponseOutputItem1
            | ResponseOutputItem2
            | ResponseOutputItem3
            | ResponseOutputItem4
            | ResponseOutputItem5
            | ResponseOutputItem6
            | ResponseOutputItem7
            | ResponseOutputItem8
            | ResponseOutputItem9
        ]
        | None,
        Field(description='Output items'),
    ] = []
    parallel_tool_calls: Annotated[
        bool | None, Field(description='Whether parallel tool calls are enabled')
    ] = True
    previous_response_id: Annotated[
        str | None, Field(description='Previous response ID if this is a continuation')
    ] = None
    reasoning: Annotated[
        ReasoningInfo | None, Field(description='Reasoning information')
    ] = None
    safety_identifier: Annotated[
        str | None, Field(description='Safety identifier for content moderation')
    ] = None
    status: Annotated[ResponseStatus, Field(description='Response status')]
    store: Annotated[
        bool | None, Field(description='Whether the response is stored')
    ] = True
    temperature: Annotated[
        float | None, Field(description='Temperature setting used')
    ] = None
    text: Annotated[TextConfig | None, Field(description='Text format settings')] = None
    tool_choice: Annotated[str | None, Field(description='Tool choice setting')] = (
        'auto'
    )
    tools: Annotated[
        list[ResponseTool1 | ResponseTool2 | ResponseTool3 | ResponseTool4] | None,
        Field(description='Available tools'),
    ] = []
    top_p: Annotated[float | None, Field(description='Top-p setting used')] = None
    truncation: Annotated[str | None, Field(description='Truncation strategy used')] = (
        None
    )
    usage: Annotated[
        UsageInfo | ResponseUsage | None, Field(description='Usage information')
    ] = None
    user: Annotated[str | None, Field(description='User identifier')] = None


class WorkerInfo(BaseModel):
    api_key: Annotated[
        str | None,
        Field(
            description='Worker API key. Accepted on input, never included in responses.'
        ),
    ] = None
    bootstrap_port: Annotated[
        int | None,
        Field(
            description='Bootstrap port for prefill workers in PD disaggregated mode.',
            ge=0,
        ),
    ] = None
    connection_mode: Annotated[
        ConnectionMode1 | ConnectionMode2 | None,
        Field(description='Connection mode: http or grpc.'),
    ] = 'http'
    cost: Annotated[
        float | None, Field(description='Worker cost factor (baseline = 1.0).')
    ] = 1.0
    dp_base_url: Annotated[
        str | None,
        Field(
            description='Base URL without DP rank suffix (for DP-aware workers). When set, `url` contains the rank-suffixed form (`{base}@{rank}`).'
        ),
    ] = None
    dp_rank: Annotated[
        int | None, Field(description='Data-parallel rank (None = not DP-aware).', ge=0)
    ] = None
    dp_size: Annotated[
        int | None,
        Field(
            description='Total data-parallel group size (None = not DP-aware).', ge=0
        ),
    ] = None
    health: Annotated[
        HealthCheckUpdate | None,
        Field(
            description='Per-worker health check overrides (partial — only `Some` fields override router defaults).'
        ),
    ] = None
    id: Annotated[str, Field(description='Worker unique identifier.')]
    is_healthy: Annotated[bool, Field(description='Whether the worker is healthy.')]
    job_status: Annotated[
        JobStatus | None,
        Field(description='Job status for async operations (if available).'),
    ] = None
    kv_connector: Annotated[
        str | None,
        Field(
            description='KV connector type (e.g. "MooncakeConnector", "NixlConnector").'
        ),
    ] = None
    kv_role: Annotated[
        str | None,
        Field(description='KV role (e.g. "kv_producer", "kv_consumer", "kv_both").'),
    ] = None
    labels: Annotated[
        dict[str, str] | None, Field(description='Additional labels/tags.')
    ] = None
    load: Annotated[int, Field(description='Current load on the worker.', ge=0)]
    load_monitor_interval_secs: Annotated[
        int | None,
        Field(
            description='Per-worker load monitor interval override (seconds). When set, workers in the same group use this interval for load polling. Falls back to the global `load_monitor_interval_secs` from router config.',
            ge=0,
        ),
    ] = None
    max_connection_attempts: Annotated[
        int | None,
        Field(
            description='Maximum connection attempts during worker registration (default: 20).',
            ge=0,
        ),
    ] = 20
    models: Annotated[
        list[ModelCard] | None, Field(description='Models this worker can serve.')
    ] = None
    priority: Annotated[
        int | None, Field(description='Worker priority (higher = preferred).', ge=0)
    ] = 50
    provider: Annotated[
        ProviderType1
        | ProviderType2
        | ProviderType3
        | ProviderType4
        | ProviderType5
        | None,
        Field(
            description='External provider for API transformations. `None` means native/passthrough.'
        ),
    ] = None
    runtime_type: Annotated[
        RuntimeType1 | RuntimeType2 | RuntimeType3 | RuntimeType4 | None,
        Field(description='Runtime type: sglang, vllm, trtllm, or external.'),
    ] = 'sglang'
    url: Annotated[str, Field(description='Worker URL.')]
    worker_type: Annotated[
        WorkerType1 | WorkerType2 | WorkerType3 | None,
        Field(description='Worker type: regular, prefill, or decode.'),
    ] = 'regular'


class ChatChoice(BaseModel):
    finish_reason: str | None = None
    hidden_states: Annotated[
        list[float] | None,
        Field(description='Hidden states from the model (SGLang extension)'),
    ] = None
    index: Annotated[int, Field(ge=0)]
    logprobs: ChatLogProbs1 | Any | None = None
    matched_stop: Annotated[
        Any | None,
        Field(description='Information about which stop condition was matched'),
    ] = None
    message: ChatCompletionMessage


class ChatCompletionRequest(BaseModel):
    chat_template_kwargs: Annotated[
        dict[str, Any] | None, Field(description='Chat template kwargs')
    ] = None
    continue_final_message: Annotated[
        bool | None,
        Field(description='Continue generating from final assistant message'),
    ] = False
    ebnf: Annotated[
        str | None, Field(description='EBNF grammar constraint for structured output')
    ] = None
    frequency_penalty: Annotated[
        float | None,
        Field(
            description='Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far',
            ge=-2.0,
            le=2.0,
        ),
    ] = None
    function_call: Annotated[
        FunctionCall1 | FunctionCall2 | None,
        Field(deprecated=True, description='Deprecated: Replaced by tool_choice'),
    ] = None
    functions: Annotated[
        list[Function] | None,
        Field(deprecated=True, description='Deprecated: Replaced by tools'),
    ] = None
    ignore_eos: Annotated[
        bool | None,
        Field(description='Ignore end-of-sequence tokens during generation'),
    ] = False
    logit_bias: Annotated[
        dict[str, Any] | None,
        Field(
            description='Modify the likelihood of specified tokens appearing in the completion'
        ),
    ] = None
    logprobs: Annotated[
        bool | None,
        Field(description='Whether to return log probabilities of the output tokens'),
    ] = False
    lora_path: Annotated[
        str | None, Field(description='Path to LoRA adapter(s) for model customization')
    ] = None
    max_completion_tokens: Annotated[
        int | None,
        Field(
            description='An upper bound for the number of tokens that can be generated for a completion',
            ge=1,
        ),
    ] = None
    max_tokens: Annotated[
        int | None,
        Field(
            deprecated=True,
            description='Deprecated: Replaced by max_completion_tokens',
            ge=1,
        ),
    ] = None
    messages: Annotated[
        list[
            ChatMessage1
            | ChatMessage2
            | ChatMessage3
            | ChatMessage4
            | ChatMessage5
            | ChatMessage6
        ],
        Field(description='A list of messages comprising the conversation so far'),
    ]
    metadata: Annotated[
        dict[str, Any] | None,
        Field(
            description='Developer-defined tags and values used for filtering completions in the dashboard'
        ),
    ] = None
    min_p: Annotated[
        float | None,
        Field(description='Min-p nucleus sampling parameter', ge=0.0, le=1.0),
    ] = None
    min_tokens: Annotated[
        int | None, Field(description='Minimum number of tokens to generate', ge=1)
    ] = None
    modalities: Annotated[
        list[str] | None,
        Field(
            description='Output types that you would like the model to generate for this request'
        ),
    ] = None
    model: Annotated[str | None, Field(description='ID of the model to use')] = (
        'unknown'
    )
    n: Annotated[
        int | None,
        Field(
            description='How many chat completion choices to generate for each input message',
            ge=1,
            le=10,
        ),
    ] = None
    no_stop_trim: Annotated[
        bool | None, Field(description='Skip trimming stop tokens from output')
    ] = False
    parallel_tool_calls: Annotated[
        bool | None,
        Field(
            description='Whether to enable parallel function calling during tool use'
        ),
    ] = None
    presence_penalty: Annotated[
        float | None,
        Field(
            description='Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far',
            ge=-2.0,
            le=2.0,
        ),
    ] = None
    prompt_cache_key: Annotated[
        str | None, Field(description='Cache key for prompts (beta feature)')
    ] = None
    reasoning_effort: Annotated[
        str | None,
        Field(description='Effort level for reasoning models (low, medium, high)'),
    ] = None
    regex: Annotated[
        str | None, Field(description='Regex constraint for output generation')
    ] = None
    repetition_penalty: Annotated[
        float | None,
        Field(
            description='Repetition penalty for reducing repetitive text',
            ge=0.0,
            le=2.0,
        ),
    ] = None
    response_format: Annotated[
        ResponseFormat1 | ResponseFormat2 | ResponseFormat3 | None,
        Field(description='An object specifying the format that the model must output'),
    ] = None
    return_hidden_states: Annotated[
        bool | None, Field(description='Return model hidden states')
    ] = False
    safety_identifier: Annotated[
        str | None, Field(description='Safety identifier for content moderation')
    ] = None
    sampling_seed: Annotated[
        int | None,
        Field(description='Random seed for sampling for deterministic outputs', ge=0),
    ] = None
    seed: Annotated[
        int | None,
        Field(
            deprecated=True, description='Deprecated: This feature is in Legacy mode'
        ),
    ] = None
    separate_reasoning: Annotated[
        bool | None,
        Field(
            description='Separate reasoning content from final answer (O1-style models)'
        ),
    ] = True
    service_tier: Annotated[
        str | None, Field(description='The service tier to use for this request')
    ] = None
    session_params: Annotated[
        dict[str, Any] | None,
        Field(description='Session parameters for continual prompting'),
    ] = None
    skip_special_tokens: Annotated[
        bool | None, Field(description='Skip special tokens during detokenization')
    ] = True
    stop: Annotated[
        str | list[str] | None,
        Field(
            description='Up to 4 sequences where the API will stop generating further tokens'
        ),
    ] = None
    stop_token_ids: Annotated[
        list[StopTokenId] | None,
        Field(description='Specific token IDs to use as stop conditions'),
    ] = None
    stream: Annotated[
        bool | None, Field(description='If set, partial message deltas will be sent')
    ] = False
    stream_options: Annotated[
        StreamOptions | None, Field(description='Options for streaming response')
    ] = None
    stream_reasoning: Annotated[
        bool | None, Field(description='Stream reasoning tokens during generation')
    ] = True
    temperature: Annotated[
        float | None,
        Field(
            description='What sampling temperature to use, between 0 and 2',
            ge=0.0,
            le=2.0,
        ),
    ] = None
    tool_choice: Annotated[
        ToolChoiceValue | ToolChoice1 | ToolChoice2 | None,
        Field(description='Controls which (if any) tool is called by the model'),
    ] = None
    tools: Annotated[
        list[Tool] | None, Field(description='A list of tools the model may call')
    ] = None
    top_k: Annotated[
        int | None, Field(description='Top-k sampling parameter (-1 to disable)')
    ] = None
    top_logprobs: Annotated[
        int | None,
        Field(
            description='An integer between 0 and 20 specifying the number of most likely tokens to return',
            ge=0,
            le=20,
        ),
    ] = None
    top_p: Annotated[
        float | None, Field(description='An alternative to sampling with temperature')
    ] = None
    verbosity: Annotated[
        int | None, Field(description='Verbosity level for debugging')
    ] = None


class ChatCompletionResponse(BaseModel):
    choices: list[ChatChoice]
    created: Annotated[int, Field(ge=0)]
    id: str
    model: str
    object: str
    system_fingerprint: str | None = None
    usage: Usage | None = None


class ChatCompletionStreamResponse(BaseModel):
    choices: list[ChatStreamChoice]
    created: Annotated[int, Field(ge=0)]
    id: str
    model: str
    object: str
    system_fingerprint: str | None = None
    usage: Usage | None = None


class ContentBlock6(BaseModel):
    content: Annotated[
        list[WebSearchResultBlock] | WebSearchToolResultError,
        Field(description='Web search tool result content'),
    ]
    tool_use_id: str
    type: Type13


class InputContentBlock10(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    content: Annotated[
        list[WebSearchResultBlock] | WebSearchToolResultError,
        Field(description='The search results or error'),
    ]
    tool_use_id: Annotated[str, Field(description='The tool use ID this result is for')]
    type: Type41


class ResponseInputOutputItem7(BaseModel):
    content: Annotated[
        str | list[ResponseContentPart1 | ResponseContentPart2 | ResponseContentPart3],
        Field(
            description='Content can be either a simple string or array of content parts (for SimpleInputMessage)'
        ),
    ]
    role: str
    type: str | None


class ResponsesRequest(BaseModel):
    background: Annotated[
        bool | None, Field(description='Run the request in the background')
    ] = None
    conversation: Annotated[
        str | None,
        Field(description='Optional conversation id to persist input/output as items'),
    ] = None
    frequency_penalty: Annotated[
        float | None, Field(description='Frequency penalty', ge=-2.0, le=2.0)
    ] = None
    include: Annotated[
        list[IncludeField] | None,
        Field(description='Fields to include in the response'),
    ] = None
    input: Annotated[
        list[
            ResponseInputOutputItem1
            | ResponseInputOutputItem2
            | ResponseInputOutputItem3
            | ResponseInputOutputItem4
            | ResponseInputOutputItem5
            | ResponseInputOutputItem6
            | ResponseInputOutputItem7
        ]
        | str,
        Field(description='Input content - can be string or structured items'),
    ]
    instructions: Annotated[
        str | None, Field(description='System instructions for the model')
    ] = None
    max_output_tokens: Annotated[
        int | None, Field(description='Maximum number of output tokens', ge=1)
    ] = None
    max_tool_calls: Annotated[
        int | None, Field(description='Maximum number of tool calls', ge=1)
    ] = None
    metadata: Annotated[
        dict[str, Any] | None, Field(description='Additional metadata')
    ] = None
    min_p: Annotated[
        float | None,
        Field(
            description='Min-p sampling parameter (SGLang extension)', ge=0.0, le=1.0
        ),
    ] = 0.0
    model: Annotated[str | None, Field(description='Model to use')] = 'unknown'
    parallel_tool_calls: Annotated[
        bool | None, Field(description='Whether to enable parallel tool calls')
    ] = None
    presence_penalty: Annotated[
        float | None, Field(description='Presence penalty', ge=-2.0, le=2.0)
    ] = None
    previous_response_id: Annotated[
        str | None, Field(description='ID of previous response to continue from')
    ] = None
    priority: Annotated[int | None, Field(description='Request priority')] = 0
    reasoning: Annotated[
        ResponseReasoningParam | None, Field(description='Reasoning configuration')
    ] = None
    repetition_penalty: Annotated[
        float | None,
        Field(description='Repetition penalty (SGLang extension)', ge=0.0, le=2.0),
    ] = 1.0
    request_id: Annotated[str | None, Field(description='Request ID')] = None
    service_tier: Annotated[
        ResponsesServiceTier | None, Field(description='Service tier')
    ] = None
    stop: Annotated[str | list[str] | None, Field(description='Stop sequences')] = None
    store: Annotated[
        bool | None, Field(description='Whether to store the response')
    ] = None
    stream: Annotated[
        bool | None, Field(description='Whether to stream the response')
    ] = None
    temperature: Annotated[
        float | None, Field(description='Temperature for sampling', ge=0.0, le=2.0)
    ] = 1.0
    text: Annotated[
        TextConfig | None,
        Field(
            description='Text format for structured outputs (text, json_object, json_schema)'
        ),
    ] = None
    tool_choice: Annotated[
        ToolChoiceValue | ToolChoice1 | ToolChoice2 | None,
        Field(description='Tool choice behavior'),
    ] = None
    tools: Annotated[
        list[ResponseTool1 | ResponseTool2 | ResponseTool3 | ResponseTool4] | None,
        Field(description='Available tools'),
    ] = None
    top_k: Annotated[
        int | None, Field(description='Top-k sampling parameter (SGLang extension)')
    ] = -1
    top_logprobs: Annotated[
        int | None, Field(description='Number of top logprobs to return', ge=0, le=20)
    ] = None
    top_p: Annotated[float | None, Field(description='Top-p sampling parameter')] = 1.0
    truncation: Annotated[
        Truncation | None, Field(description='Truncation behavior')
    ] = None
    user: Annotated[str | None, Field(description='User identifier')] = None


class ContentBlock10(BaseModel):
    content: (
        str
        | list[
            ToolResultContentBlock1
            | ToolResultContentBlock2
            | ToolResultContentBlock3
            | ToolResultContentBlock4
        ]
        | None
    ) = None
    is_error: bool | None = None
    tool_use_id: str
    type: Type17


class CreateMessageRequest(BaseModel):
    container: Annotated[
        ContainerConfig | None,
        Field(description='Container configuration for code execution (beta).'),
    ] = None
    max_tokens: Annotated[
        int,
        Field(
            description='The maximum number of tokens to generate before stopping.',
            ge=1,
        ),
    ]
    mcp_servers: Annotated[
        list[McpServerConfig] | None,
        Field(description='MCP servers to be utilized in this request (beta).'),
    ] = None
    messages: Annotated[
        list[InputMessage],
        Field(description='Input messages for the conversation.', min_length=1),
    ]
    metadata: Annotated[
        Metadata | None,
        Field(description='An object describing metadata about the request.'),
    ] = None
    model: Annotated[
        str,
        Field(description='The model that will complete your prompt.', min_length=1),
    ]
    service_tier: Annotated[
        ServiceTier | None,
        Field(description='Service tier for the request (auto or standard_only).'),
    ] = None
    stop_sequences: Annotated[
        list[str] | None,
        Field(
            description='Custom text sequences that will cause the model to stop generating.'
        ),
    ] = None
    stream: Annotated[
        bool | None,
        Field(
            description='Whether to incrementally stream the response using server-sent events.'
        ),
    ] = None
    system: Annotated[
        str | list[TextBlock] | None,
        Field(description='System prompt for providing context and instructions.'),
    ] = None
    temperature: Annotated[
        float | None,
        Field(
            description='Amount of randomness injected into the response (0.0 to 1.0).'
        ),
    ] = None
    thinking: Annotated[
        ThinkingConfig1 | ThinkingConfig2 | None,
        Field(description='Configuration for extended thinking.'),
    ] = None
    tool_choice: Annotated[
        MessagesToolChoice1
        | MessagesToolChoice2
        | MessagesToolChoice3
        | MessagesToolChoice4
        | None,
        Field(description='How the model should use the provided tools.'),
    ] = None
    tools: Annotated[
        list[
            McpToolset
            | CustomTool
            | ToolSearchTool
            | BashTool
            | TextEditorTool
            | WebSearchTool
        ]
        | None,
        Field(description='Definitions of tools that the model may use.'),
    ] = None
    top_k: Annotated[
        int | None,
        Field(
            description='Only sample from the top K options for each subsequent token.',
            ge=0,
        ),
    ] = None
    top_p: Annotated[float | None, Field(description='Use nucleus sampling.')] = None


class DocumentSource4(BaseModel):
    content: list[
        InputContentBlock1
        | InputContentBlock2
        | InputContentBlock3
        | InputContentBlock4
        | InputContentBlock5
        | InputContentBlock6
        | InputContentBlock7
        | InputContentBlock8
        | InputContentBlock9
        | InputContentBlock10
        | InputContentBlock11
        | InputContentBlock12
    ]
    type: Type29


class InputContentBlock3(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    citations: Annotated[
        CitationsConfig | None, Field(description='Citations configuration')
    ] = None
    context: Annotated[
        str | None, Field(description='Optional context for the document')
    ] = None
    source: Annotated[
        DocumentSource1 | DocumentSource2 | DocumentSource3 | DocumentSource4,
        Field(description='The document source'),
    ]
    title: Annotated[
        str | None, Field(description='Optional title for the document')
    ] = None
    type: Type34


class InputContentBlock5(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    content: Annotated[
        str
        | list[
            ToolResultContentBlock1
            | ToolResultContentBlock2
            | ToolResultContentBlock3
            | ToolResultContentBlock4
        ]
        | None,
        Field(description='The result content (string or blocks)'),
    ] = None
    is_error: Annotated[
        bool | None, Field(description='Whether this result indicates an error')
    ] = None
    tool_use_id: Annotated[
        str, Field(description='The ID of the tool use this is a result for')
    ]
    type: Type36


class InputMessage(BaseModel):
    content: Annotated[
        str
        | list[
            InputContentBlock1
            | InputContentBlock2
            | InputContentBlock3
            | InputContentBlock4
            | InputContentBlock5
            | InputContentBlock6
            | InputContentBlock7
            | InputContentBlock8
            | InputContentBlock9
            | InputContentBlock10
            | InputContentBlock11
            | InputContentBlock12
        ],
        Field(description='The content of the message'),
    ]
    role: Annotated[
        RoleModel,
        Field(description='The role of the message sender (user or assistant)'),
    ]


class Message(BaseModel):
    content: Annotated[
        list[
            ContentBlock1
            | ContentBlock2
            | ContentBlock3
            | ContentBlock4
            | ContentBlock5
            | ContentBlock6
            | ContentBlock7
            | ContentBlock8
            | ContentBlock9
            | ContentBlock10
        ],
        Field(description='Content generated by the model'),
    ]
    id: Annotated[str, Field(description='Unique object identifier')]
    model: Annotated[str, Field(description='The model that generated the message')]
    role: Annotated[str, Field(description='Conversational role (always "assistant")')]
    stop_reason: Annotated[
        StopReason1
        | StopReason2
        | StopReason3
        | StopReason4
        | StopReason5
        | StopReason6
        | None,
        Field(description='The reason the model stopped generating'),
    ] = None
    stop_sequence: Annotated[
        str | None,
        Field(description='Which custom stop sequence was generated (if any)'),
    ] = None
    type: Annotated[str, Field(description='Object type (always "message")')]
    usage: Annotated[MessagesUsage, Field(description='Billing and rate-limit usage')]


class MessageStreamEvent1(BaseModel):
    message: Message
    type: Type43


class MessageStreamEvent4(BaseModel):
    content_block: Annotated[
        ContentBlock1
        | ContentBlock2
        | ContentBlock3
        | ContentBlock4
        | ContentBlock5
        | ContentBlock6
        | ContentBlock7
        | ContentBlock8
        | ContentBlock9
        | ContentBlock10,
        Field(description='Output content block types'),
    ]
    index: Annotated[int, Field(ge=0)]
    type: Type46


class ToolResultContentBlock3(BaseModel):
    cache_control: Annotated[
        CacheControl | None, Field(description='Cache control for this block')
    ] = None
    citations: Annotated[
        CitationsConfig | None, Field(description='Citations configuration')
    ] = None
    context: Annotated[
        str | None, Field(description='Optional context for the document')
    ] = None
    source: Annotated[
        DocumentSource1 | DocumentSource2 | DocumentSource3 | DocumentSource4,
        Field(description='The document source'),
    ]
    title: Annotated[
        str | None, Field(description='Optional title for the document')
    ] = None
    type: Type95


class MessageStreamEvent(
    RootModel[
        MessageStreamEvent1
        | MessageStreamEvent2
        | MessageStreamEvent3
        | MessageStreamEvent4
        | MessageStreamEvent5
        | MessageStreamEvent6
        | MessageStreamEvent7
        | MessageStreamEvent8
    ]
):
    root: Annotated[
        MessageStreamEvent1
        | MessageStreamEvent2
        | MessageStreamEvent3
        | MessageStreamEvent4
        | MessageStreamEvent5
        | MessageStreamEvent6
        | MessageStreamEvent7
        | MessageStreamEvent8,
        Field(description='Server-sent event wrapper', title='MessageStreamEvent'),
    ]


ContentBlock10.model_rebuild()
CreateMessageRequest.model_rebuild()
DocumentSource4.model_rebuild()
InputContentBlock5.model_rebuild()
