{{- if eq .Values.mode "router-worker" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smg.fullname" . }}-worker
  labels:
    {{- include "smg.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.worker.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "smg.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
{{- end }}
