name: 'Setup vLLM Backend'
description: 'Create Python venv, restore pip cache, and install vLLM.'

runs:
  using: 'composite'
  steps:
    - name: Setup Python venv
      shell: bash
      run: bash scripts/ci_setup_python_venv.sh

    - name: Restore pip cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: vllm-pip-${{ runner.os }}-${{ hashFiles('scripts/ci_install_vllm.sh') }}

    - name: Install vLLM
      shell: bash
      run: bash scripts/ci_install_vllm.sh
