name: 'Setup vLLM Backend'
description: 'Create Python venv and install vLLM.'

runs:
  using: 'composite'
  steps:
    - name: Setup Python venv
      shell: bash
      run: bash scripts/ci_setup_python_venv.sh

    - name: Install vLLM
      shell: bash
      run: bash scripts/ci_install_vllm.sh
