apiVersion: v1
kind: Secret
metadata:
  name: github-arc-secret
  namespace: actions-runner-system
type: Opaque
stringData:
  github_app_id: "2703284"
  github_app_installation_id: "105440663"
  github_app_private_key: "github-app-private-key"
