apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-runner-sa
  namespace: actions-runner-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-runner
  namespace: actions-runner-system
rules:
  # Argo Workflows
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch

  # Pods
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/exec
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runner-rb
  namespace: actions-runner-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-runner
subjects:
  - kind: ServiceAccount
    name: arc-runner-sa
    namespace: actions-runner-system
