name: 'Setup SGLang Backend'
description: 'Create Python venv, restore/save pip cache, and install SGLang.'

runs:
  using: 'composite'
  steps:
    - name: Setup Python venv
      shell: bash
      run: bash scripts/ci_setup_python_venv.sh

    - name: Restore pip cache
      id: pip-cache
      uses: actions/cache/restore@v4
      with:
        path: ~/.cache/pip
        key: sglang-pip-${{ runner.os }}-${{ hashFiles('scripts/ci_install_sglang.sh') }}

    - name: Install SGLang
      shell: bash
      run: bash scripts/ci_install_sglang.sh

    - name: Save pip cache
      if: steps.pip-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ~/.cache/pip
        key: sglang-pip-${{ runner.os }}-${{ hashFiles('scripts/ci_install_sglang.sh') }}
