name: 'Setup SGLang Backend'
description: 'Create Python venv and install SGLang.'

runs:
  using: 'composite'
  steps:
    - name: Setup Python venv
      shell: bash
      run: bash scripts/ci_setup_python_venv.sh

    - name: Install SGLang
      shell: bash
      run: bash scripts/ci_install_sglang.sh
